### ISSUE TITLE
XML cross-updates

### ISSUE THREAD

**Issue by yegor256** [zerocracy/datum#100]
Let's create XSLs for cross updates of XML documents. When a modification happens to, say `orders.xml`, we should automatically update, say, `elections.xml`.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#100` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+2430](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#100` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+2475](http://www.0crat.com/u/yegor256).
