### ISSUE TITLE
[bot] apply call without a project id triggers TelegramApiRequestException

### ISSUE THREAD

**Issue by kkamkou** [zerocracy/datum#102]
Reproduce:
- type `apply` without id.

Exception:
```
1.0-SNAPSHOT 11f7099 2017-08-25T18:40:02
IllegalStateException: java.lang.reflect.InvocationTargetException
org.telegram.telegrambots.exceptions.TelegramApiRequestException: Error sending message: [400] Bad Request: can't parse entities in message text: Can't find end of the entity starting at byte offset 54
 at org.telegram.telegrambots.api.methods.send.SendMessage.deserializeResponse(SendMessage.java:170)
 at org.telegram.telegrambots.api.methods.send.SendMessage.deserializeResponse(SendMessage.java:24)
 at org.telegram.telegrambots.bots.DefaultAbsSender.sendApiMethod(DefaultAbsSender.java:605)
 at com.zerocracy.radars.telegram.TmZerocrat.reply(TmZerocrat.java:93)
 at com.zerocracy.radars.telegram.TmBotSession.reply(TmBotSession.java:52)
 at com.zerocracy.radars.telegram.TmSession$reply.call(Unknown Source)
 at com.zerocracy.stk.pm.comm.notify_telegram.exec(notify_telegram.groovy:36)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Delegati...
```

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#102` assigned to @g4s8, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by g4s8** [comment]
@kkamkou try now please, it should be fixed.

**Comment by g4s8** [comment]
@kkamkou could you please check it? It was fixed in zerocracy/farm#272 PR. // cc @yegor256

**Comment by kkamkou** [comment]
Yes, I'll do it tomorrow morning.

**Comment by kkamkou** [comment]
@yegor256 please restart the instance, the reply time is about 3 mins and behavior is strange.

**Comment by kkamkou** [comment]
resolved (looks good), refs #146

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:zerocracy/datum#102`.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#102` is now out of scope.

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/datum/issues/102#issuecomment-353790291))

@g4s8 Oops! Job `gh:zerocracy/datum#102` is not assigned to anyone.

**Comment by g4s8** [comment]
@0crat resign

**Comment by 0crat** [comment]
> @0crat resign ([here](https://github.com/zerocracy/datum/issues/102#issuecomment-355100317))

@g4s8 Oops! Job `gh:zerocracy/datum#102` is not assigned, can't get performer

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/datum/issues/102#issuecomment-355355588))

@g4s8 Job `gh:zerocracy/datum#102` assigned to @g4s8  ([profile](http://www.0crat.com/u/g4s8})). The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read the [Policy](http://datum.zerocracy.com/pages/policy.html) and go ahead.

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [par.19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @g4s8, total is [+2890](http://www.0crat.com/u/g4s8).

**Comment by g4s8** [comment]
@0crat resign

**Comment by 0crat** [comment]
> @0crat resign ([here](https://github.com/zerocracy/datum/issues/102#issuecomment-355356313))

@g4s8 @g4s8 resigned from `gh:zerocracy/datum#102`, please stop working.
