### ISSUE TITLE
Too many issues assigned to a new person without rate

### ISSUE THREAD

**Issue by kkamkou** [zerocracy/datum#103]
Recently I've registered for a new project. Having `rate=0`, the system has assigned 15 issues to me.

Reproduce (Telegram bot is used):
- `apply #12345`
- go to the [agenda](http://www.0crat.com/u/kkamkou/agenda) page

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#103` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by yegor256** [comment]
@kkamkou won't happen again, it's fixed

**Comment by 0crat** [comment]
@yegor256 resigned from `gh:zerocracy/datum#103`, please stop working.

**Comment by yegor256** [comment]
@kkamkou do you still see the problem? Please, check. I believe, it's fixed.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#103` assigned to @g4s8, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#103` is not assigned to anyone.

**Comment by 0crat** [comment]
@g4s8 resigned from `gh:zerocracy/datum#103`, please stop working.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#103` assigned to @caarlos0, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by yegor256** [comment]
@kkamkou I believe it's fixed already, please check.

**Comment by kkamkou** [comment]
@yegor256 the problem was for a new person. I can't leave the project there is another exception. For an existing person most probably it is fixed as I have only limited number of issues assigned to me.

**Comment by yegor256** [comment]
@kkamkou why can't you leave the project?

**Comment by kkamkou** [comment]
@yegor256 now it works and I see: `You are not in the project C63314D6Z anymore.`. The previous reply was in  `something went wrong` context (check the logs, I'm sure you can trace the reason).

I've sent a new join request.

**Comment by yegor256** [comment]
@kkamkou you have a role now, let's see what happens.

**Comment by kkamkou** [comment]
nothing so far, will check it tomorrow

**Comment by kkamkou** [comment]
I got two of them. Resolved.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#103` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @caarlos0, total is [+615](http://www.0crat.com/u/caarlos0).
