### ISSUE TITLE
[bot][telegram] help message design issue

### ISSUE THREAD

**Issue by kkamkou** [zerocracy/datum#104]
Not all commands are displayed correctly.

![2017-08-29-d1a9ea7](https://user-images.githubusercontent.com/305739/29838162-ae35dd3c-8cfa-11e7-911b-1cf5e8e48d82.png)

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#104` assigned to @g4s8, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by g4s8** [comment]
@kkamkou try now, it should be fixed

**Comment by kkamkou** [comment]
Confirmed. It looks okay. Thank you.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#104` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @g4s8, total is [+2365](http://www.0crat.com/u/g4s8).
