### ISSUE TITLE
show path in each entry, in index.xml

### ISSUE THREAD

**Issue by yegor256** [zerocracy/datum#106]
Let's show path there, for each entry

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#106` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+2595](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `0.38.1`

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#106` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+2640](http://www.0crat.com/u/yegor256).
