### ISSUE TITLE
extract prefix and sort by it, in index.xml

### ISSUE THREAD

**Issue by yegor256** [zerocracy/datum#107]
Let's extract numeric prefixes and sort by them.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#107` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+2610](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `0.39`

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#107` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+2670](http://www.0crat.com/u/yegor256).
