### ISSUE TITLE
Performer cannot refuse issue

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#111]
https://github.com/DronMDF/telebot/issues/1#issuecomment-326663725

His say: "Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project."

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@DronMDF it was a bug, fixed, thanks!

**Comment by yegor256** [comment]
@DronMDF please check

**Comment by DronMDF** [comment]
@yegor256 This is work. Thank's

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:zerocracy/datum#111`.

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#111` is not in scope.
