### ISSUE TITLE
0crat not control performing time.

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#112]
https://github.com/DronMDF/telebot/issues/2#issuecomment-322831774

Issue assigned 16 days ago.
0crat should reassign it after 10 days.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#112` assigned to @g4s8, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
Open issue for example:
https://github.com/DronMDF/telebot/issues/1
https://github.com/DronMDF/telebot/issues/2 is closed by me.

**Comment by DronMDF** [comment]
@g4s8 This is a very useful feature and I would like to see it.
up. :)

**Comment by g4s8** [comment]
@DronMDF it's in progress, it will be implemented right after github reminder notifications

**Comment by g4s8** [comment]
@DronMDF looks like it's working, see https://github.com/yegor256/pdd/issues/77#issuecomment-344290215

**Comment by DronMDF** [comment]
@g4s8 Yes, resign by time works.

But:

1. I do not see the election of a new performer, so it should be?
2. Some problem with numbers (was assigned to you 8 days ago .... taken away from you after 10 days from start).

**Comment by g4s8** [comment]
@DronMDF 
> I do not see the election of a new performer, so it should be?

I think it should, @yegor256 right?

> Some problem with numbers

It's different things: reminders should be posted on issue after 5 days and after 8 days,
but issue should be resigned after 10 days: http://datum.zerocracy.com/pages/policy.html#8

**Comment by DronMDF** [comment]
@g4s8 election was not happens. Only regular 0crat cry... :(

**Comment by 0crat** [comment]
@g4s8 resigned from `gh:zerocracy/datum#112`, please stop working.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#112` assigned to @g4s8, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Oops! You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "0crat").

**Comment by 0crat** [comment]
@g4s8 resigned from `gh:zerocracy/datum#112`, please stop working.

**Comment by DronMDF** [comment]
0crat elect new performer.
This is work.
Thank's

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:zerocracy/datum#112`.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#112` is now out of scope.
