### ISSUE TITLE
Authorization issue

### ISSUE THREAD

**Issue by kkamkou** [zerocracy/datum#113]
Reproduce (via web):
- go to `http://www.0crat.com/`
- Click `Login`, it is okay.
- Click on `@me` link
- It shows: `You "@me" must be invited to us by someone we already know. If you don't know anyone who works with us already, email us to join@zerocracy.com and we'll see what we can do.`

Reproduce (via Telegram bot)
- Chat `help`
- It says: `I don't know who you are, please click here: http://www.0crat.com/alias?href=me&rel=telegram`
- Click on the link
- Message is the same as via web

@yegor256 in case I don't have permissions anymore (if my account was deleted), please show me another message.

**Comment by kkamkou** [comment]
Invalid, I was excluded from the system.

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#113` was not in scope
