### ISSUE TITLE
Resigned performer сontinues to remain responsible for the issue.

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#118]
This work assigned to @roman901.
https://github.com/DronMDF/telebot/issues/1

The role DEV was resigned.

There is no DEV in the project http://www.0crat.com/a/C6KLDT6QG?a=pm/staff/roles

Issue stay order to performer.
![image](https://user-images.githubusercontent.com/2982959/30534480-182e7cf0-9c67-11e7-942e-a3d68d3d9c9a.png)

May be i have problem with names? spark vs roman901.

PS: And 0crat not control performing time by #112.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@DronMDF that's a bug. We must not allow you to remove DEV role from a person, if there are tasks. Let me fix it now.

**Comment by DronMDF** [comment]
Thank's

**Comment by yegor256** [comment]
@DronMDF on the second thought I believe that we should not change anything. Having a role in the project only means that the person will participate in elections and will receive new tasks. If you remove the role, the person gets no tasks anymore. But he still has the tasks you assigned him earlier. See?

**Comment by DronMDF** [comment]
@yegor256 May be.
I can resign issue.
But I do not see the possibility of releasing the task from the performer. #135.

**Comment by yegor256** [comment]
@DronMDF I commented in #135. It seems that this issue can be closed.

**Comment by DronMDF** [comment]
@yegor256 Ok.
But 'out' should lead to the stop of works. It will be right.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:zerocracy/datum#118`.

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#118` was not in scope

**Comment by yegor256** [comment]
@DronMDF you will have to do `reject` first and then `out`. Just `out` won't work, since the order is open. It's an extra protection, I believe it makes sense.
