### ISSUE TITLE
PO and ARC is not assigned to project.

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#119]
0Crat say: "You're in no projects yet, apply to some of them."

![image](https://user-images.githubusercontent.com/2982959/30740905-870d4034-9f9b-11e7-981f-3e26936640d3.png)

I'm is PO! I'm is ARC!

![image](https://user-images.githubusercontent.com/2982959/30740960-b8760480-9f9b-11e7-8498-5d2379ff31ce.png)

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@DronMDF I believe it's fixed, please check now

**Comment by DronMDF** [comment]
Yes, this is fixed.
Thank's.

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#119` was not in scope
