### ISSUE TITLE
Inviting is hard.

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#122]
I invited people to Slask.
After that, each person should send me github login so that I can invite him.
This is a many copypaste process.
May be 0crat may give me a link for inviting? for each user?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#122` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by yegor256** [comment]
@DronMDF make sense, let us think about it

**Comment by DronMDF** [comment]
I Think...
I invite users to a specific Slack channel.
0crat know what project is being developed on this channel?
After hello 0crat can send inviting url to admin... May be.

I spent 45 minutes to envy 25 people. :)

**Comment by 0crat** [comment]
@yegor256 resigned from `gh:zerocracy/datum#122`, please stop working.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#122` assigned to @caarlos0, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@caarlos0 resigned from `gh:zerocracy/datum#122`, please stop working.

**Comment by 0crat** [comment]
The job [#122](https://github.com/zerocracy/datum/issues/122) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by g4s8** [comment]
@DronMDF @yegor256 what do you think about invite links:

1. when you want to invite somebody you ask chat bot `invite` without arguments, it will generate unique invite link
2. you send this link to a user you want to invite
3. when user click this link the site will ask to authorize via Github and add him to users

**Comment by yegor256** [comment]
@g4s8 how can we guarantee that the link won't be clicked by someone else? Or many other people?

**Comment by 0crat** [comment]
Job [#122](https://github.com/zerocracy/datum/issues/122) is already in scope

**Comment by DronMDF** [comment]
We can go on the other side. Let new users go to the 0crat.com and enter the name of the mentor who invites them. The mentor will receive a link to confirm each.

Although maybe this is not a problem at all?

**Comment by g4s8** [comment]
@yegor256 it will be one-time link with expiration time (like reset-password link), if someone click this link it will not be available anymore.

**Comment by g4s8** [comment]
@0crat waiting
@yegor256 what do you say about comments: https://github.com/zerocracy/datum/issues/122#issuecomment-361706124 and https://github.com/zerocracy/datum/issues/122#issuecomment-362694077

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zerocracy/datum/issues/122#issuecomment-362844936). You must always start your message with my name if you want to address it to me, see [§1](http://datum.zerocracy.com/pages/policy.html#1).

**Comment by g4s8** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/zerocracy/datum/issues/122#issuecomment-362844996))

@g4s8 The impediment for [#122](https://github.com/zerocracy/datum/issues/122) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by yegor256** [comment]
@g4s8 I think this is how we will proceed: https://github.com/zerocracy/farm/issues/520

**Comment by g4s8** [comment]
@DronMDF please, look at https://www.0crat.com/join
also zerocracy/farm#502 was submited. Can we close this bug?

**Comment by 0crat** [comment]
To cancel the order use `refuse` as in [§6](http://datum.zerocracy.com/pages/policy.html#6)

**Comment by DronMDF** [comment]
@g4s8 Yes, join form is good. I should close it?

**Comment by g4s8** [comment]
@DronMDF yes, if you agree that inviting will be easier with this form

**Comment by DronMDF** [comment]
Thank's

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+4330](https://www.0crat.com/u/g4s8)
