### ISSUE TITLE
As a PO, I want to have project statistics.

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#123]
How many points did each developer earn?
How many issues did the project accomplish?
etc.

Thanks.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#123` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Manual assignments of jobs are discouraged, see par.19: -5 points just awarded to @yegor256, total is [+3640](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@DronMDF I created the first version of some reporting. Check "Reports" tab in your project page and please close this ticket. If you need more reports, please open new tickets per each report.

**Comment by DronMDF** [comment]
@yegor256 Ok, Thank's.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#123` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256, total is [+4095](http://www.0crat.com/u/yegor256).
