### ISSUE TITLE
Distribution issue to performer is not fair.

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#126]
I have 18 performers, and 7 issue.
In first moment all issue assign to one performer.
In this situation should be assigned 7 any performers. I think.
Next issue should be assign to any free performer.

If issues is many then performers - 0crat should select the most free.

Thank's.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@DronMDF I belive this problem is fixed already. Now we assign evenly. Please check.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#126` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
At first glance it distributes evenly.
Thanks.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#126` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+3495](http://www.0crat.com/u/yegor256).
