### ISSUE TITLE
Orders page contains a lot of information.

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#127]
If this information is need, it should be hide by default.
May be turn on by url parameter? 

http://www.0crat.com/a/C6KLDT6QG?a=pm/in/orders&verbose

I look only one job on screen... Does not fit anymore.
Not. I have two screen per job... :)

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.41.1`

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#127` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by yegor256** [comment]
@DronMDF check now please

**Comment by DronMDF** [comment]
This is a readable now. Thanks.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#127` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+3465](http://www.0crat.com/u/yegor256).
