### ISSUE TITLE
0crat not react on command in message body (not in first line)

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#130]
https://github.com/dronmdf/telebot/issues/18#issuecomment-333638846
0crat ignore it.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@DronMDF it didn't ignore it, just took a bit longer than usual.

**Comment by DronMDF** [comment]
@yegor256 Let's try here. :)
@0crat in

**Comment by DronMDF** [comment]
Apparently he does not want to talk to me. :)

**Comment by yegor256** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/zerocracy/datum/issues/130#issuecomment-333980442))

@yegor256 Job `gh:zerocracy/datum#130` is in scope.

**Comment by yegor256** [comment]
@DronMDF talks to me though :) I think the problem is that you should always start a message with `@0crat`. Otherwise, it won't answer. I will fix it now though.

**Comment by yegor256** [comment]
Hey, @0crat how are you?

**Comment by 0crat** [comment]
Are you speaking to me or about me? You must always start your message with my name if you want to address it to me.

**Comment by yegor256** [comment]
@0crat hey

**Comment by 0crat** [comment]
> @0crat hey ([here](https://github.com/zerocracy/datum/issues/130#issuecomment-333984643))

@yegor256 Hey, what's up, how is it going?

**Comment by yegor256** [comment]
@DronMDF it seems to be working?

**Comment by yegor256** [comment]
@0crat how are you?

**Comment by 0crat** [comment]
> @0crat how are you? ([here](https://github.com/zerocracy/datum/issues/130#issuecomment-337840143))

@yegor256 Can't understand "how", try one of these:
  - `assign` Assign a performer to this issue
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Remove this issue from scope (WBS)
  - `resign` Resign from this issue
  - `version` Print current version of the bot

**Comment by DronMDF** [comment]
He says about start message, probably ok.
@0crat Do you agree? :)

**Comment by 0crat** [comment]
Are you speaking to me or about me? You must always start your message with my name if you want to address it to me.

**Comment by DronMDF** [comment]
Ok.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:zerocracy/datum#130`.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#130` is now out of scope.
