### ISSUE TITLE
The user does not see the project to which it is connected.

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#131]
![image](https://user-images.githubusercontent.com/2982959/31167712-a70fd8ba-a8fb-11e7-9fd2-9ca2aa2ca88e.png)

In his profile hi not assign in project.
![image](https://user-images.githubusercontent.com/2982959/31167743-c6742b5c-a8fb-11e7-8b48-5ebe6212697c.png)

And he's not alone in my group with a similar problem.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@DronMDF are you sure this user has a role in the project?

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#131` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
Look at first screenshot...
Look in roles: http://www.0crat.com/a/C6KLDT6QG?a=pm/staff/roles
Look at gh issue: https://github.com/dronmdf/telebot/issues/22
0crat know him.

**Comment by DronMDF** [comment]
@yegor256 How did you assign the job to yourself? I do not see any commands.

**Comment by yegor256** [comment]
@DronMDF see https://github.com/zerocracy/datum/commit/20a21137bceb26a7ec701e43cf4693314d8c86f0

**Comment by DronMDF** [comment]
@yegor256 :+1:
But why do you add commands that are contrary to the principles? :)
You have to be tougher.

**Comment by DronMDF** [comment]
![image](https://user-images.githubusercontent.com/2982959/31177656-577d281a-a91f-11e7-82c7-4caaa36453f9.png)
Another user with same problem.

**Comment by yegor256** [comment]
@DronMDF this is fixed. In the future, every time a new job gets assigned to a developer, his list of projects will be updated.

**Comment by DronMDF** [comment]
if I enter the URL with my hands, I see the profile of any user. but if I click on a link, I get into my tasks.

**Comment by DronMDF** [comment]
![image](https://user-images.githubusercontent.com/2982959/31194278-5443626a-a94f-11e7-8e84-c40a57af657a.png)
This is a invisea profile for me.
Look at url, at name and at jobs. I no have jobs.

**Comment by yegor256** [comment]
@DronMDF is it still an issue?

**Comment by DronMDF** [comment]
@yegor256 I'll ask.

**Comment by 0crat** [comment]
@yegor256 resigned from `gh:zerocracy/datum#131`, please stop working.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#131` assigned to @caarlos0, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by yegor256** [comment]
@DronMDF I believe it's fixed, please check

**Comment by DronMDF** [comment]
@yegor256 In my profile the project is present. Ok, Thank's.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#131` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @caarlos0, total is [+555](http://www.0crat.com/u/caarlos0).
