### ISSUE TITLE
The bot reacts to the commands on the githab for a long time.

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#132]
https://github.com/DronMDF/telebot/issues/37
34 minutes have passed since the command was given.

And this is not the limit.
https://github.com/DronMDF/telebot/issues/36
64 minutes have passed.

It's very slow.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by DronMDF** [comment]
2,5 hours left from in.
https://github.com/DronMDF/telebot/issues/49#issuecomment-336401104
And not assign.

**Comment by yegor256** [comment]
@DronMDF there were temporary problems on our side. Should be fine now.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:zerocracy/datum#132`.

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#132` was not in scope
