### ISSUE TITLE
Closed PR remain in the job list.

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#133]
![image](https://user-images.githubusercontent.com/2982959/31408920-c57bf506-ae12-11e7-826a-eaa475262653.png)

Last two is a merged PR.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by DronMDF** [comment]
@yegor256 This is a big problem...
Merged PR litter the task list.

**Comment by yegor256** [comment]
@DronMDF it seems that the problem is that some webhook messages from GitHub are missed. Please, use this URL for the webhook: `http://p.rehttp.net/http://www.0crat.com/ghook`

**Comment by DronMDF** [comment]
@yegor256 May be...
I see problem in deliveries.
![image](https://user-images.githubusercontent.com/2982959/31682687-88a2aab4-b383-11e7-83e8-3cb0bda3da9a.png)
hook updated.

**Comment by yegor256** [comment]
@DronMDF yes, exactly my point. Because of that problems, some events from GitHub could be missed. Let's monitor now.

**Comment by yegor256** [comment]
@DronMDF there is some other problem. I will fix it now.

**Comment by yegor256** [comment]
@DronMDF I believe it's fixed, please check

**Comment by DronMDF** [comment]
@yegor256 Ok, tranks.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:zerocracy/datum#133`.

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#133` is not in scope.
