### ISSUE TITLE
There is no way to remove the issue from the scope without scoring.

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#135]
The developer disappeared, and the task became not relevant.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@DronMDF just say `out` or `refuse`. `out` will remove the task from scope entirely. `refuse` will terminate current order and un-assign the performer.

**Comment by DronMDF** [comment]
@yegor256 i cannot say 'out', although it would be a good idea.
https://github.com/DronMDF/telebot/issues/51#issuecomment-337852903

**Comment by yegor256** [comment]
@DronMDF first, you have to cancel the order (using `reject`) and only then you can remove it from the scope.

**Comment by yegor256** [comment]
@DronMDF This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#135` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#135](https://github.com/zerocracy/datum/issues/135) was not in scope

**Comment by DronMDF** [comment]
Thank's
