### ISSUE TITLE
Empty awards statistics

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#136]
![image](https://user-images.githubusercontent.com/2982959/31759653-c6f00acc-b4ba-11e7-873f-ebd94184a812.png)

Total is zero.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@DronMDF it's a bug. All new awards will be added to the `total` column. previous awards are lost :(
