### ISSUE TITLE
Unrecoverable failure format

### ISSUE THREAD

**Issue by filfreire** [zerocracy/datum#140]
The unrecoverable failure messages seem to be wrongly formatted, view example bellow:
<img width="511" alt="screen shot 2017-10-23 at 19 28 19" src="https://user-images.githubusercontent.com/11976836/31906418-f6d97ebe-b828-11e7-915a-7f8add6e6e14.png">

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum): 

```
 java.lang.AssertionError: HTTP response status is not equal to 200:
404 Not Found [https://api.github.com/repos/zerocracy/datum/issues/140]
Server: GitHub.com
Date: Mon, 23 Oct 2017 18:33:10 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Status: 404 Not Found
X-RateLimit-Limit: 5000
X-RateLimit-Remaining: 4981
X-RateLimit-Reset: 1508786764
X-GitHub-Media-Type: github.v3
Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
Access-Control-Allow-Origin: *
Expect-CT: max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"
Content-Security-Policy: default-src 'none'
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-Runtime-Rack: 0.053345
X-GitHub-Request-Id: 91E0:19256:10349D5:21521FB:59EE35E6

{"message":"Not... 
```

 My version: `%s`, `%s`, `%s`. Cc @yegor256 1.0-SNAPSHOT 39785cc 2017-10-23T12:21:13

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@filfreire it's fixed, thanks!

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:zerocracy/datum#140`.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:zerocracy/datum#140`.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:zerocracy/datum#140`.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:zerocracy/datum#140`.

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#140` is not in scope.
