### ISSUE TITLE
more information in XSLs

### ISSUE THREAD

**Issue by yegor256** [zerocracy/datum#141]
Let's add more information there.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#141` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @yegor256, total is [+4365](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @yegor256, total is [+4365](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `0.43.1`

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#141` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256, total is [+4395](http://www.0crat.com/u/yegor256).
