### ISSUE TITLE
[telegram] apply doesn't do the id validation

### ISSUE THREAD

**Issue by kkamkou** [zerocracy/datum#146]
Request: `apply ABCRDFG11`
Reply: `Project ABCRDFG11 was notified about your desire to join them.`
Expected: `is not found` variant

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@kkamkou should be fine now, please try

**Comment by kkamkou** [comment]
> Oops! Project "ABCRDFG11" doesn't exist.
Works as expected.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:zerocracy/datum#146`.

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#146` is not in scope.
