### ISSUE TITLE
0crat not control lifetime of PR

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#149]
https://github.com/DronMDF/telebot/pull/92

This closed before scope in.
After 7 days 0crat close it and pay.
After 0crat assign it again...

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@DronMDF This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#149` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#149](https://github.com/zerocracy/datum/issues/149) was not in scope

**Comment by DronMDF** [comment]
Ok, Thanks...
