### ISSUE TITLE
No reaction to the command 'out'.

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#157]
https://github.com/DronMDF/telebot/pull/97

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@DronMDF it was a temporary bug, fixed already, thanks.

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#157` is not assigned, can't get start time

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#157` was not in scope

**Comment by DronMDF** [comment]
@yegor256 Thanks.
