### ISSUE TITLE
How to close project?

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#159]

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.49`

**Comment by yegor256** [comment]
@rultor release, tag is `0.49`

**Comment by yegor256** [comment]
@DronMDF you can now use `pause` command or completely destroy the project with `destroy`. Please try.

**Comment by DronMDF** [comment]
@yegor256 Project was not paused

![image](https://user-images.githubusercontent.com/2982959/34409133-def8baa6-ebd8-11e7-98c9-0b3b66cf19bc.png)

Next question: How to unpause project?

**Comment by yegor256** [comment]
@DronMDF say `pause on` or `pause off`

**Comment by DronMDF** [comment]
@yegor256 Policy say - 'pause'... not 'pause on'

http://datum.zerocracy.com/pages/policy.html#24

pause is not worked.
	
dron 9:44 PM
@0crat pause
0cratAPP 9:44 PM
@dron Oops! The project is alive (not on pause). To change the status say `pause on` or `pause off`.

destroy is work.

**Comment by 0crat** [comment]
Are you speaking to me or about me? You must always start your message with my name if you want to address it to me.

**Comment by yegor256** [comment]
@DronMDF I modified the error messages, it should be all clear now

**Comment by DronMDF** [comment]
@yegor256 Thank's

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#159` is not assigned, can't get start time

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#159` was not in scope
