### ISSUE TITLE
Misprint in the policy: paragraph 20: "bitcon" instead of "bitcoin"

### ISSUE THREAD

**Issue by skapral** [zerocracy/datum#162]

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@skapral fixed already, thanks!

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#162` is not assigned, can't get start time

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#162` was not in scope
