### ISSUE TITLE
After getting invitation to the slack channel, 0crat bot is too verbose.

### ISSUE THREAD

**Issue by skapral** [zerocracy/datum#163]
Steps to reproduce:

0. After inviting 0crat to the workspace
1. Create a channel and invite 0crat to there.

Actual result: 0crat responds with lots of "Thanks for inviting me here." messages.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#163` assigned to [@g4s8](http://www.0crat.com/u/g4s8}). The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read [§4](http://datum.zerocracy.com/pages/policy.html#4), [§8](http://datum.zerocracy.com/pages/policy.html#8), and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256, total is [+6665](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
[@g4s8](http://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@g4s8[/z](http://www.0crat.com/u/g4s8) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat waiting

**Comment by 0crat** [comment]
The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#163](https://github.com/zerocracy/datum/issues/163), please stop working

**Comment by 0crat** [comment]
Job [#163](https://github.com/zerocracy/datum/issues/163) is already in scope

**Comment by 0crat** [comment]
The job [#163](https://github.com/zerocracy/datum/issues/163) assigned to @caarlos0[/z](https://www.0crat.com/u/caarlos0). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
The user @caarlos0[/z](https://www.0crat.com/u/caarlos0) resigned from [#163](https://github.com/zerocracy/datum/issues/163), please stop working

**Comment by 0crat** [comment]
The job [#163](https://github.com/zerocracy/datum/issues/163) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/610869115). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by t-izbassar** [comment]
@skapral is this is still relevant issue? I've tried to invite Zerocracy to slack and it's seems ok now.

**Comment by t-izbassar** [comment]
@skapral yes it is still relevant. Sorry for distraction. Just invited zerocracy to the channel.

**Comment by t-izbassar** [comment]
@0crat waiting for [PR](https://github.com/zerocracy/farm/pull/744) to be merged

**Comment by 0crat** [comment]
> @0crat waiting for [PR](https://github.com/zerocracy/farm/pull/744) to be merged ([here](https://github.com/zerocracy/datum/issues/163#issuecomment-371100383))

@t-izbassar You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `DEV`.

**Comment by 0crat** [comment]
> @0crat waiting for [PR](https://github.com/zerocracy/farm/pull/744) to be merged ([here](https://github.com/zerocracy/datum/issues/163#issuecomment-371100383))

@t-izbassar The impediment for [#163](https://github.com/zerocracy/datum/issues/163) was registered successfully by @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by t-izbassar** [comment]
@skapral it’s fixed in #744. Can you close this one?

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#163](https://github.com/zerocracy/datum/issues/163) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +30 points just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
