### ISSUE TITLE
Fix error found in Cactoos (poor error description/stack trace only)

### ISSUE THREAD

**Issue by allanwsilva** [zerocracy/datum#165]
As detailed [here](https://github.com/yegor256/cactoos/pull/402#issuecomment-323025529)

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@allanwsilva fixed already, thanks for reporting

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#165` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#165](https://github.com/zerocracy/datum/issues/165) was not in scope
