### ISSUE TITLE
@0crat waiting not implemented(?)

### ISSUE THREAD

**Issue by allanws** [zerocracy/datum#166]
I tried to use @0crat waiting command ([as in the policy](http://datum.zerocracy.com/pages/policy.html#9)) and it didn't work...

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@allanws works already, please try

**Comment by allanws** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/zerocracy/datum/issues/166#issuecomment-356134387))

@allanws Oops! Job `gh:zerocracy/datum#166` is not assigned, can't put it on hold

**Comment by allanws** [comment]
@yegor256 , it seems to be working, but I'm not aware of its whole lifecycle. Is there any documentation to test it?

**Comment by yegor256** [comment]
@allanws it just puts the job on hold, that's all. Nothing else happens.

**Comment by allanws** [comment]
@yegor256 , that's OK.

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#166` is not assigned, can't get start time

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#166` was not in scope
