### ISSUE TITLE
java.lang.ClassCastException: org.glassfish.json.JsonObjectBuilderImpl$JsonObjectImpl cannot be cast to javax.json.JsonString

### ISSUE THREAD

**Issue by allanws** [zerocracy/datum#167]
As per in this [comment](https://github.com/yegor256/cactoos/issues/420#issuecomment-336510365)

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by allanws** [comment]
This might fix this [issue](https://github.com/yegor256/cactoos/issues/413) too.

**Comment by yegor256** [comment]
@allanws this is too old, fixed already

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#167` is not assigned, can't get start time

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#167` was not in scope
