### ISSUE TITLE
roles in policy must be explained

### ISSUE THREAD

**Issue by yegor256** [zerocracy/datum#168]

**Comment by yegor256** [comment]
@rultor release, tag is `0.51`

**Comment by yegor256** [comment]
@rultor release, tag is `0.50`

**Comment by yegor256** [comment]
@rultor release, tag is `0.51`

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#168` is not assigned, can't get start time

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#168` was not in scope
