### ISSUE TITLE
Profile link is broken

### ISSUE THREAD

**Issue by allanws** [zerocracy/datum#170]
As in [here](https://github.com/yegor256/cactoos/pull/402#issuecomment-355361005)

(rubbish at the end of the URL - character '%7D')

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@allanws fixed already, thanks!

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#170` is not assigned, can't get start time

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#170` was not in scope
