### ISSUE TITLE
After merge error

### ISSUE THREAD

**Issue by allanws** [zerocracy/datum#171]
As in [here](https://github.com/yegor256/cactoos/pull/402#issuecomment-355949175)

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@allanws it's fixed already, thanks

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#171` is not assigned, can't get start time

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#171` was not in scope
