### ISSUE TITLE
How do I check my profile?

### ISSUE THREAD

**Issue by allanws** [zerocracy/datum#172]
Should the user/member profile be listed in the 'profile page' (http://www.0crat.com/u/<user>) according to the project? 

A user can have multiple profiles within a project as well...

Profiles may have different rates associated as well...

Please see if all this makes sense...

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@allanws please, report one problem per ticket.
