### ISSUE TITLE
0crat is computing time/task assignment in a wrong fashion

### ISSUE THREAD

**Issue by allanws** [zerocracy/datum#173]
As per this [comment](https://github.com/yegor256/cactoos/pull/507#issuecomment-355954119).

My comments were the latest ones and, as per my understanding, that would mean the ticket is not on my shoulders, but the bot was sucking my time instead.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@allanws see this: http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html It doesn't matter who is saying what, the ticket is yours until it's closed. But it is not relevant to pull requests, see ecf3bbc

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#173` is not assigned, can't get start time

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#173` was not in scope
