### ISSUE TITLE
Telegram bot requests with empty argument

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/datum#175]
If you request in telegram bot with empty argument - nothing happens. Examples:
* `apply`
* `wallet`

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#175` is not assigned, can't get start time

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#175` was not in scope
