### ISSUE TITLE
How to see all assigned jobs?

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/datum#176]
I've got jobs assignment. Now I need to go to the projects, find mentioned issue from chat with bot, which is some manual steps to do.

Maybe there should be some bot request for listing jobs. Or some board with all assignments so that it will be easier to find them and go to link to the issue. Simple step that will help is to get an url link to the jobs issue in current implementation.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by t-izbassar** [comment]
Ok. I found it in the profile) Maybe just mention somewhere where to find them so it could be more clear. And I have this xml. Browser is Mozzila (57.0.4 (64-bit)) on Ubuntu 16.04:
![image](https://user-images.githubusercontent.com/24223260/34693773-2bcd1b52-f4c5-11e7-9051-2ff9939c4a89.png)

**Comment by t-izbassar** [comment]
The issue #189 is more specific so closing this one.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#176` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#176` was not in scope
