### ISSUE TITLE
Should issues be 'formally' assigned?

### ISSUE THREAD

**Issue by allanws** [zerocracy/datum#177]
I don't see any of the issues assigned to people... shouldn't they be marked as assigned in Github?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by fabriciofx** [comment]
@allanws @yegor256 It could create a label with username of the DEV and associate to the issue. WDYT?

**Comment by yegor256** [comment]
@allanws it's not possible to assign tickets to strangers, only to official contributors.
