### ISSUE TITLE
My agenda is showing one task (PR) but there is no mention to me on the PR itself

### ISSUE THREAD

**Issue by allanwsilva** [zerocracy/datum#178]
My [agenda](http://www.0crat.com/u/allanws/agenda) lists this [issue](https://github.com/yegor256/cactoos/pull/477), but apparently there is nothing explicitly assigned to me.

Please fix it.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by allanws** [comment]
@yegor256 , please have a look at this issue as this is affecting my agenda. Thanks.

**Comment by yegor256** [comment]
@allanws definitely a bug, we will take a look, thanks for reporting!

**Comment by 0crat** [comment]
Job [#178](https://github.com/zerocracy/datum/issues/178) is now in scope, role is `DEV`

**Comment by yegor256** [comment]
@allanwsilva This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#178` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#178](https://github.com/zerocracy/datum/issues/178) is now out of scope
