### ISSUE TITLE
List user profiles per project

### ISSUE THREAD

**Issue by allanws** [zerocracy/datum#179]
In the agenda page, for every project, list all profiles assigned to the user.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@allanws I didn't understand. How a profile can be assigned to a user?)

**Comment by allanws** [comment]
@yegor256 each user is in a project may have multiple roles like REV, DEV, ARC, etc. Showing those in the agenda page might be helpful.. for example, I know I can be REV in a project, and expect just PRs and in another project I can be DEV or ARC as well...

This is just an idea, up to you to decide whether or not to be implemented.

**Comment by yegor256** [comment]
@allanws that's a good idea.

@g4s8 let's add `role` element to the agenda.

**Comment by yegor256** [comment]
@g4s8 also the `estimate`

**Comment by 0crat** [comment]
The job [#179](https://github.com/zerocracy/datum/issues/179) assigned to g4s8. The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to [@yegor256](http://www.0crat.com/u/yegor256), total is [+6985](http://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@g4s8[/z](http://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@allanws please check your agenda page, now all jobs have a role, for all previous jobs `DEV` role was set. Can we close this bug?

**Comment by g4s8** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/zerocracy/datum/issues/179#issuecomment-359170244))

@g4s8 The impediment was registered successfully

**Comment by allanws** [comment]
@g4s8 tha's it, thanks! 

Who can close this issue?

**Comment by g4s8** [comment]
> Who can close this issue?
@allanws you (author)

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+3355](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#179](https://github.com/zerocracy/datum/issues/179) is now out of scope
