### ISSUE TITLE
Starting on Desktop is different than starting on mobile app.

### ISSUE THREAD

**Issue by filfreire** [zerocracy/datum#180]
Is it normal to have to start on a different platform if one already as started on one?
Example, on January 3rd I `/start`via Telegram Desktop.

When I write something on Telegram for Android, I'm invited to associate a new alias with my 0crat account.

Examples:
- Starting on Desktop:
![screen shot 2018-01-09 at 08 01 37](https://user-images.githubusercontent.com/11976836/34710528-a2d6ad28-f513-11e7-9c23-8723ebbfecd8.png)

- Afterwards, writing on same Telegram channel, but via Mobile (Telegram for Android):
![screen shot 2018-01-09 at 08 02 03](https://user-images.githubusercontent.com/11976836/34710546-afe31808-f513-11e7-93a2-c0cac337994f.png)

/cc @yegor256

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@filfreire each channel has its own ID, I believe. You can safely start as many of them as possible. We identify you always by GitHub ID.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#180` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#180](https://github.com/zerocracy/datum/issues/180) was not in scope
