### ISSUE TITLE
Is the "Oops!" string necessary when getting rate value?

### ISSUE THREAD

**Issue by filfreire** [zerocracy/datum#181]
After setting up a rate (via Telegram chat), if I write down only `rate`, I get the following message:

> Oops! Your rate is $10.00. To change it just say rate $25, for example.

Does the `Oops!` part of the sentence make sense? As a user, I might want to simply check what's my current rate.

Screenshot:
![screen shot 2018-01-09 at 08 05 58](https://user-images.githubusercontent.com/11976836/34710681-4077492a-f514-11e7-99f1-c11358d4cad2.png)

/cc @yegor256

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@filfreire fixed, no more `Oops`

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#181` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#181` was not in scope
