### ISSUE TITLE
Support capital letters

### ISSUE THREAD

**Issue by filfreire** [zerocracy/datum#182]
In a lot of cases, when a user starts writing down a command via a smartphone (example Telegram for Android or Telegram for iOS) the keyboard is usually set to assume the first letter is high-caps and not low caps.

Does it make sense that `0crat` bot should be able to read commands written with the first letter in caps?

Example screenshot:
![screen shot 2018-01-09 at 08 11 48](https://user-images.githubusercontent.com/11976836/34710844-c462ea32-f514-11e7-8c04-38aa422d420a.png)

/cc @yegor256

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@filfreire thanks, fixed

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#182` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#182](https://github.com/zerocracy/datum/issues/182) was not in scope
