### ISSUE TITLE
Are other currencies supported?

### ISSUE THREAD

**Issue by filfreire** [zerocracy/datum#183]
It seems that other currencies, other than US dollars ($) are supported

Default, US Dollars:
![screen shot 2018-01-09 at 08 13 43](https://user-images.githubusercontent.com/11976836/34710931-218f149c-f515-11e7-87d5-458e44de191b.png)

Example, Euros:
![screen shot 2018-01-09 at 08 13 36](https://user-images.githubusercontent.com/11976836/34710928-1ef5703c-f515-11e7-97a2-bcb160d3b481.png)

But there doesn't seem to be a reference inside the [policy](http://datum.zerocracy.com/pages/policy.html) about this fact.

So, are other currencies officially supported?

/cc @yegor256

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@filfreire explained in 82e73e2

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#183` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#183](https://github.com/zerocracy/datum/issues/183) was not in scope
