### ISSUE TITLE
Is the "Oops!" string necessary when getting the current wallet?

### ISSUE THREAD

**Issue by filfreire** [zerocracy/datum#184]
Similar to Issue #181 but for the `wallet` command.

> Oops! Your wallet is someones_email@email_provider.com at "paypal".

Does the `Oops!` part of the sentence make sense? As a user, I might want to simply check what's my current wallet configuration.

/cc @yegor256

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@filfreire fixed, thanks!

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#184` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#184](https://github.com/zerocracy/datum/issues/184) was not in scope
