### ISSUE TITLE
Support for "help" command for 0crat chat bot.

### ISSUE THREAD

**Issue by filfreire** [zerocracy/datum#185]
As a user, I might want to get the list of commands via the typical `help` command. It seems 0crat bot doesn't know that command, instead of prints out the typical error message for an unknown command.

Example screenshot:
![screen shot 2018-01-09 at 08 20 58](https://user-images.githubusercontent.com/11976836/34711195-5d3bed8e-f516-11e7-95e3-d2648ac9327a.png)

Does it make sense to create a help command that lists more options and contains the link to the [policy](http://datum.zerocracy.com/pages/policy.html)?

/cc @yegor256

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@filfreire that's a good idea, but we are trying to keep the list of commands as short as possible. Let's not add more than we really need. Thanks.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#185` is not assigned, can't get start time
