### ISSUE TITLE
0crat doesn't tag the Github assignee correctly

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/datum#186]
0crat assigned 2 tasks on Github to me, but it did not tag me correctly. It did write ``@amihaiemil``, but it is a link to http://www.0crat.com/u/amihaiemil instead of a proper Github tag. See [here](https://github.com/yegor256/cactoos/pull/487#issuecomment-356231495)

As a result, I did not receive a notification email from Github that I had two tasks assigned. They were invisible, apart from the fact that they appear on my 0crat.com agenda.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@yegor256[/z](http://www.zerocracy.com)

**Comment by yegor256** [comment]
@amihaiemil fixed, thanks!

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#186` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#186](https://github.com/zerocracy/datum/issues/186) was not in scope
