### ISSUE TITLE
Add possibility to set rate saying 'rate 10$'

### ISSUE THREAD

**Issue by iCok** [zerocracy/datum#187]
Ocrat bot does not understand command `rate 10$` and answer with:
`Oops! Can't parse cash value pair "10$"`

But from my opinion `10$` more natural way of typing, how it looks like in a shops.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by fabriciofx** [comment]
@iCok I don't know which country do you live, but to to me most countries use the currency symbol before the value, or don't?

**Comment by iCok** [comment]
I looked around, you are right.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#187` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#187](https://github.com/zerocracy/datum/issues/187) was not in scope
