### ISSUE TITLE
Commands instead of words for telegram bot

### ISSUE THREAD

**Issue by nick318** [zerocracy/datum#188]
As far as I know for telegram bots it is more useful use commands like `/command_name`.
In that case all available commands and parameters will be visible instantly.

So I suggest to change words to typical commands in telegram bot.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by fabriciofx** [comment]
@iCok Please, could you give us an example? Thanks in advance.

**Comment by iCok** [comment]
![image](https://user-images.githubusercontent.com/6926262/34810158-09e5800c-f6b3-11e7-88b7-9304ad73aac7.png)

When bot has commands and I type slash I see following.

**Comment by 0crat** [comment]
Job [#188](https://github.com/zerocracy/datum/issues/188) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#188](https://github.com/zerocracy/datum/issues/188) assigned to g4s8. The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to [@yegor256](http://www.0crat.com/u/yegor256), total is [+7330](http://www.0crat.com/u/yegor256)

**Comment by g4s8** [comment]
@0crat waiting for zerocracy/farm#411

**Comment by 0crat** [comment]
> @0crat waiting for zerocracy/farm#411 ([here](https://github.com/zerocracy/datum/issues/188#issuecomment-359237185))

@g4s8 The impediment was registered successfully

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/datum/issues/188#issuecomment-361631548))

@yegor256 This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#188](https://github.com/zerocracy/datum/issues/188) is [in scope](http://datum.zerocracy.com/pages/policy.html#14) for 15days
  * The role is `DEV`
  * The job is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8) for [15days](http://datum.zerocracy.com/pages/policy.html#8)
  * There is a monetary reward attached
  * @g4s8[/z](https://www.0crat.com/u/g4s8) will get 0.00 of their hourly rate for this job
  * Some equity will be [vested](http://datum.zerocracy.com/pages/policy.html#37) on completion
  * The job has an [impediment](http://datum.zerocracy.com/pages/policy.html#9)
  * The [budget](http://datum.zerocracy.com/pages/policy.html#4) is 30 minutes
  * These users are banned and won't be assigned:
    * @icok[/z](https://www.0crat.com/u/icok): This user reported the ticket

**Comment by 0crat** [comment]
Job [#188](https://github.com/zerocracy/datum/issues/188) is already in scope

**Comment by g4s8** [comment]
@nick318 please, look at telegram bot now, this bug should be fixed.

**Comment by 0crat** [comment]
To cancel the order use `refuse` as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by nick318** [comment]
@g4s8 yep, fixed

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+4600](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#188](https://github.com/zerocracy/datum/issues/188) is now out of scope
