### ISSUE TITLE
0crat add invalid link (with } and the end) to profile

### ISSUE THREAD

**Issue by janczer** [zerocracy/datum#190]
For example in this [comment](https://github.com/yegor256/jpeek/pull/52#issuecomment-356228810) 0crat add link to `@janczer`:

```
http://www.0crat.com/u/janczer}
```

Another [one](https://github.com/yegor256/jpeek/pull/87#issuecomment-356234219) example

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by amihaiemil** [comment]
@janczer that link is not OK either way, it should be a Github tag, so I get a mail from Github that I was tagger somewhere...

**Comment by yegor256** [comment]
@janczer it's fixed already, thanks

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#190` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#190](https://github.com/zerocracy/datum/issues/190) was not in scope
