### ISSUE TITLE
0crat add me job for role REV but I have role DEV

### ISSUE THREAD

**Issue by janczer** [zerocracy/datum#191]
[Proof](https://github.com/yegor256/jpeek/pull/52#issuecomment-356228810)

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by iCok** [comment]
similar issue [https://github.com/yegor256/cactoos/pull/527](pull request)

**Comment by t-izbassar** [comment]
+1
[PR](https://github.com/jcabi/jcabi-w3c/pull/39)

**Comment by yegor256** [comment]
@janczer I believe it's fixed already. Please, keep an eye on this problem and report again, if you see it.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#191` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#191](https://github.com/zerocracy/datum/issues/191) was not in scope

**Comment by janczer** [comment]
@yegor256 Ok, thank you. So what I should do with this [job](https://github.com/yegor256/jpeek/pull/52#issuecomment-356228810)? Can you delete it from my jobs or I should tell about it to 0crat?

**Comment by yegor256** [comment]
@janczer you can reject it: http://datum.zerocracy.com/pages/policy.html#6
