### ISSUE TITLE
0crat doesn't grant me PO role in my own project.

### ISSUE THREAD

**Issue by skapral** [zerocracy/datum#192]
Steps:

http://datum.zerocracy.com/pages/policy.html
1. Created workspace on slack, invited 0crat there (paragraph 11).

2. Created a channel, invited 0crat there (paragraph 12)
@0crat responded with "Thanks for inviting me here" multiple times (issue #163)

3. Tried to make myself a PO (paragraph 13)
```
@0crat assign PO skapral 0

@skapralov You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "skapral").
```

4. Tried to link GitHub to the channel (paragraph 17)

```
@0crat  links add github project-avral/oo-atom

@skapralov You need to have one of these roles in order to do what you're trying to do: PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "skapral").
```

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by skapral** [comment]
@yegor256, is there some way to work around this issue on 0crat side? I wish I couuld participate in testing 0crat, but for now I am kinda blocked with it.

**Comment by yegor256** [comment]
@skapral try to say `bootstrap` to it in the Slack channel

**Comment by skapral** [comment]
It helped. I bootstrapped the project, linked it with GitHub account. IMO it is worth to update paragraph 12 also and explicitly describe that bootstrap command.

Thanks.

**Comment by yegor256** [comment]
@rultor release, tag is `0.51.3`

**Comment by yegor256** [comment]
@skapral check the policy now, should be fine, I believe

**Comment by yegor256** [comment]
@skapral This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#192` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#192](https://github.com/zerocracy/datum/issues/192) was not in scope
