### ISSUE TITLE
waiting command does not work

### ISSUE THREAD

**Issue by iCok** [zerocracy/datum#193]
According to issue #166 waiting command does not work again.
I was trying to use it [here](https://github.com/yegor256/cactoos/pull/527)

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/datum/issues/193#issuecomment-356677939))

@yegor256 This is what I know about this job:

  * The job [#193](https://github.com/zerocracy/datum/issues/193) is not in scope

**Comment by yegor256** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/zerocracy/datum/issues/193#issuecomment-356678894))

@yegor256 Job `gh:zerocracy/datum#193` is not assigned, can't put it on hold

**Comment by yegor256** [comment]
@iCok it was a bug, thanks for reporting. Fixed. Please try again.

**Comment by iCok** [comment]
@yegor256 it seems to work, but there is an exception after that command.
check it out: https://github.com/yegor256/jpeek/pull/54

**Comment by yegor256** [comment]
@iCok also fixed, thanks

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#193` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#193](https://github.com/zerocracy/datum/issues/193) was not in scope
