### ISSUE TITLE
How to see you role in the project?

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/datum#197]
On the board I have a list of projects and on agenda there are list of tasks. But how to see the role?

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@t-izbassar you should see roles inside the agenda

**Comment by yegor256** [comment]
@t-izbassar This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#197` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#197](https://github.com/zerocracy/datum/issues/197) was not in scope
