### ISSUE TITLE
0crat doesn't recognise me as DEV role

### ISSUE THREAD

**Issue by fabriciofx** [zerocracy/datum#198]
I don't know I'm not recognized as DEV by 0crat. Could be it a bug?

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@fabriciofx This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#198` is not assigned, can't get start time
