### ISSUE TITLE
Suggestion: the same person opened an issue has preference to solve it

### ISSUE THREAD

**Issue by fabriciofx** [zerocracy/datum#199]
I've a suggestion: what do you think the same person (DEV, ARC, or other) opened an issue to have the preference to solve it? I think this idea will improve the bugs search and solutions by all DEVs.

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@fabriciofx this would be against our principles of bug tracking. A bug must be solved by someone else, not the author. See: http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#199` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#199](https://github.com/zerocracy/datum/issues/199) was not in scope
