### ISSUE TITLE
0crat list my agenda with already merged jobs (but not closed)

### ISSUE THREAD

**Issue by fabriciofx** [zerocracy/datum#200]
I don't know why 0crat list my agenda with already merged jobs (but not closed). You can see them [here](https://github.com/yegor256/cactoos/pull/425) and [here](https://github.com/yegor256/cactoos/pull/424).

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@fabriciofx This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by yegor256** [comment]
@fabriciofx we will continue here: https://github.com/zerocracy/farm/issues/496

**Comment by 0crat** [comment]
Job [#200](https://github.com/zerocracy/datum/issues/200) was not in scope
