### ISSUE TITLE
0crat doesn't obey the 10 days deadline to reassign the issue to other DEV

### ISSUE THREAD

**Issue by fabriciofx** [zerocracy/datum#201]
I think 0crat doesn't obey the 10 days deadline to reassign the issue to other DEV. You can see this problem [here](https://github.com/yegor256/cactoos/issues/262). Please, pay attention to days showed by GitHub.

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@fabriciofx This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#201` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#201](https://github.com/zerocracy/datum/issues/201) was not in scope
