### ISSUE TITLE
Suggestion: Let's improve 0crat commands usage message

### ISSUE THREAD

**Issue by fabriciofx** [zerocracy/datum#202]
I think could be interesting improve the commands usage message. For example, `apply` command. I think would be better some thing like `apply <ID>` where `ID` is the `ID` of the project. I think it's more clear.

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@fabriciofx but that's exactly how it works now: `apply ID`

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#202` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#202](https://github.com/zerocracy/datum/issues/202) was not in scope
