### ISSUE TITLE
Suggestion: Let's add the help command to 0crat

### ISSUE THREAD

**Issue by fabriciofx** [zerocracy/datum#203]
Let's add the `help` command to 0crat. Today, only if a write a wrong command it will show me the commands list. It would be nice if I've a `help` command.

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by fabriciofx** [comment]
Duplicate of #185 .

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#203` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#203](https://github.com/zerocracy/datum/issues/203) was not in scope
