### ISSUE TITLE
Suggestion: Let's add a policy command to 0crat

### ISSUE THREAD

**Issue by fabriciofx** [zerocracy/datum#204]
Let's add a `policy` command to 0crat to show the [policy](http://datum.zerocracy.com/pages/policy.html). WDYT?

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@fabriciofx it's a funny idea, but what for? :) We have a link to policy on the site.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#204` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#204](https://github.com/zerocracy/datum/issues/204) was not in scope
