### ISSUE TITLE
0crat assign issues to me in a repo that I don't have access

### ISSUE THREAD

**Issue by fabriciofx** [zerocracy/datum#205]
0crat assign issues to me in repo that I don't have access, like [this](https://github.com/zerocracy/farm/issues/135).

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@fabriciofx you do have access to that repo

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#205` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#205](https://github.com/zerocracy/datum/issues/205) was not in scope
