### ISSUE TITLE
I don't see the "Close" button in the PR I'm assigned to

### ISSUE THREAD

**Issue by allanws** [zerocracy/datum#208]
@yegor256 , if I decide to close [this PR](https://github.com/yegor256/cactoos/pull/507), I just can't because the "Close" button is not visible to me... thoughts?

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@allanws it's not your PR, why do you want to close it? :) Also, read this please: http://datum.zerocracy.com/pages/policy.html#27

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#208` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#208](https://github.com/zerocracy/datum/issues/208) was not in scope

**Comment by allanws** [comment]
@yegor256 , please pay attention to [**this issue**](https://github.com/yegor256/cactoos/pull/507) (mentioned in the [**first comment**](https://github.com/zerocracy/datum/issues/208#issue-287965258) as well...)

**Comment by yegor256** [comment]
@allanws I did pay attention to it. It's not your PR, you can't close it.

**Comment by allanws** [comment]
What does that mean then (please see pic attached)?

![image](https://user-images.githubusercontent.com/5676363/34966368-4422bbc2-faaf-11e7-8e19-7a9142187b0d.png)
