### ISSUE TITLE
Negative point after reuse

### ISSUE THREAD

**Issue by janczer** [zerocracy/datum#209]
Policy says nothing about point bellow 0.
I understand if I haven't any points then 0crat can't do anything.

Or if I have 5 points and get -15 point for reuse, I will be have -10 or 0?

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@janczer I believe it's a wrong assumption. The policy never said that points can only be positive. Negative points are possible.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#209` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#209](https://github.com/zerocracy/datum/issues/209) was not in scope
