### ISSUE TITLE
0crat assign PR like a job

### ISSUE THREAD

**Issue by janczer** [zerocracy/datum#210]
According to this [comments](https://github.com/zerocracy/datum/issues/191#issuecomment-356903230) I report it again.

After I `reuse` this [job](https://github.com/yegor256/jpeek/pull/52) 0crat [assign](https://github.com/yegor256/jpeek/pull/52#issuecomment-357241942) someone else to this PR again.

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by t-izbassar** [comment]
+1. [PR](https://github.com/yegor256/cactoos/pull/527)
+1 [PR](https://github.com/jcabi/jcabi-simpledb/pull/10)

**Comment by yegor256** [comment]
@janczer it's fixed already, thanks

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#210` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#210](https://github.com/zerocracy/datum/issues/210) was not in scope
