### ISSUE TITLE
0crat doesn't actually do any assigning

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/datum#211]
0crat mentions the assignee in a comment and registers the task in its system but it should also assign the user on the Github issue or on the PR.

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil it assigns a user, if possible. GitHub doesn't allow us to do that if you are not a contributor.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#211` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#211](https://github.com/zerocracy/datum/issues/211) was not in scope
