### ISSUE TITLE
Give users ability to contribute funds to the project

### ISSUE THREAD

**Issue by skapral** [zerocracy/datum#212]
Idea is to let the users of the product, managed by ZC, contribute their money to support the product. Some sort of croudfunding. It can be implemented in the following way.

1. Owner of GitHub repository places some badge like "support us" or "give us all your money!"

2. By clicking the badge, stripe form is opened

3. User submits the credit card information and is charged for some predefined amount of money

4. Contributed money are placed to the ZC project's fundings.

Additionally, some badges may be added to indicate current amount of funds and target amount the project require for some milestone.

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@skapral interesting idea. You mean contribution to _any_ project or only to Zerocracy?

**Comment by skapral** [comment]
@yegor256 I meant "contributing funds to the projects which are managed by Zerocracy". It is more easy and straightforward than doing it for any projects in Github, because projects under ZC already have everything - a project's budget and a capability to put money in it, managed by ZC.

**Comment by yegor256** [comment]
@skapral how about this:

1. You make your project "openly fundable" by telling Zerocrat to do that.

2. All finances and statistics of the project become fully available for anyone (not only PO) -- for audit purposes.

3. You can accept funds from anyone, we will provide a Stripe button with a fixed amount (say, $64, $256, or $1024).

4. You can place that button anywhere -- either in your GitHub repo or on your website -- it's public.

I don't know why anyone would donate anything to any open source projects, but we can give it a try :) WDYT?

**Comment by skapral** [comment]
@yegor256 it's totally ok for me.

> I don't know why anyone would donate anything to any open source projects, but we can give it a try :) 

If you think it makes no sense, I am ok closing it. But the same question actually may be raised from PO perspective: why and from where should he pay contributors for contributing to open-source project? From his own pocket?

A bit of off-topic: actually, I had more ideas to this:
 - Croudfunding on a particular project features: scenario would be like - an issue with some cool but significant proposal is created, croudfunding for it is announced, and until the funds for it are collected, it is not approved and scoped.
 - Putting investors to contribution list

I can create more issues on that, if you are interested.

**Comment by yegor256** [comment]
@skapral let me implement it and we'll see how it works. Let's keep the ticket open.

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9045](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#212](https://github.com/zerocracy/datum/issues/212) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/572005665). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/datum/issues/212#issuecomment-370245614))

@g4s8 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#212](https://github.com/zerocracy/datum/issues/212) is [in scope](http://www.zerocracy.com/policy.html#14) for 1mon
  * The role is `DEV`
  * The job is assigned to @g4s8[/z](https://www.0crat.com/u/g4s8) for [6days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @g4s8[/z](https://www.0crat.com/u/g4s8) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @skapral[/z](https://www.0crat.com/u/skapral): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Fdatum%23212%27%7D) (restricted area)

**Comment by g4s8** [comment]
@yegor256 you've [self-assigned](https://github.com/zerocracy/datum/issues/212#event-1452975288) this ticket, but 0crat reassigned it to me

**Comment by yegor256** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/datum/issues/212#issuecomment-370456717))

@yegor256 The job [#212](https://github.com/zerocracy/datum/issues/212) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/641534366). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@skapral I will implement it here: https://github.com/zerocracy/farm/issues/866

**Comment by 0crat** [comment]
The job [#212](https://github.com/zerocracy/datum/issues/212) is now out of scope
