### ISSUE TITLE
Is it possible to use Zerocracy with incomplete team?

### ISSUE THREAD

**Issue by skapral** [zerocracy/datum#213]
1. I noticed that Zerocracy allows combining some roles to one person, like ARC and PO. But disallows to combine ARC and QA for example. It's worth to describe these combinations in detail in policy.

2. It's not always possible to have a separate REV or QA, especially at a very beginning. Which roles may be omitted from the methodology and how this will affect the pipeline. It's worth to have this information in Policy

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@see http://datum.zerocracy.com/pages/policy.html#34 Is this enough?

**Comment by skapral** [comment]
IMO it is also worth to mention that PO and ARC roles may be assigned at one person, and PO and QA cannot.

**Comment by skapral** [comment]
Also, policy states that there must be one ARC for the project, but initially created, it has no ARC in there, only the PO. Is it unusable until ARC is assigned? Maybe policy should explicitly say somewhere near bootstrap paragraphs that first thing PO must do is to assign ARC?

**Comment by skapral** [comment]
@yegor256 FYI

**Comment by yegor256** [comment]
@skapral we assign both `PO` and `ARC` now, when you bootstrap a project.

**Comment by yegor256** [comment]
@skapral I'm in general against verbosity in policy. If something is absolutely necessary to say there, we say it there. Otherwise, there is no reason to explain obvious things -- the user will see them when he/she tries to do something with the bot.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#213` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#213](https://github.com/zerocracy/datum/issues/213) was not in scope
