### ISSUE TITLE
Impediments do not work, 9 point of policy

### ISSUE THREAD

**Issue by iCok** [zerocracy/datum#215]
According to [policy](http://datum.zerocracy.com/pages/policy.html#9) impediments should stop counting 10 days rule. But I have notifications about deadline of that task:
https://github.com/yegor256/jpeek/pull/54

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@iCok it was a bug, fixed already. Please, report it again, if you see it.
