### ISSUE TITLE
Implements self-assigned issues as open source contributions

### ISSUE THREAD

**Issue by fabriciofx** [zerocracy/datum#216]
Let's implement self-assigned issues as open source contributions, where these contributions will be scored but not remunerated.

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@fabriciofx that's against the very principle of "tasking". Creating problems and then solving them -- it's just wrong.

**Comment by fabriciofx** [comment]
@yegor256 IMHO, I can't see any problem with it. You could assign a REV to this PR, if you want to confirm the code quality. Besides, you don't think using this model will hinder opensource contributions? Because it's simpler to contributing something I know what is the problem and how I can fix it.

**Comment by yegor256** [comment]
@fabriciofx of course, you can do it, but why do you need 0crat than? Just do it.

**Comment by fabriciofx** [comment]
@yegor256 IMHO, we need 0crat to organize and assign who is doing what and the all others remunerated cases.

**Comment by yegor256** [comment]
@fabriciofx so, let 0crat do that according to his principles :) If you want to break the rules, you can always do that, but that will be outside of the process 0crat is managing.

**Comment by fabriciofx** [comment]
@yegor256 Ok, but how we deal with the problem of anybody report an issue and do a PR, but how the issue is not assigned to him, other DEV will take the PR and submit as the (original) developer? All kudos go to the assigned DEV not to person who developed the PR.

**Comment by yegor256** [comment]
@fabriciofx just submit a PR directly, without an issue. Open source projects work like that. They don't report issues first and PRs next. Just submit your code in PRs.
