### ISSUE TITLE
A more detailed (and smart) agenda

### ISSUE THREAD

**Issue by fabriciofx** [zerocracy/datum#217]
It would be nice if 0crat to show a more detailed agenda, for example:

1. When a REV finished a review, it will be showed in agenda "Review done, waiting for DEV" or something like that;
2. When a DEV submit a PR, will be showed in agenda "PR submited, waiting for review" or something like that;
3. When a Job has been concluded, will be showed in agenda "Job finished" or something like that.

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@fabriciofx it's against our principles. We don't pay attention to the details of a job. It's either 0 or 100 for us: either open or closed. Also, remember that one job can have multiple pull requests or even none.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#217` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#217](https://github.com/zerocracy/datum/issues/217) was not in scope
