### ISSUE TITLE
0crat points to a wrong paragraph in the policy

### ISSUE THREAD

**Issue by fabriciofx** [zerocracy/datum#219]
When I use the command `apply ID $16` the 0crat telegram bot show me:
```
Your reputation is 195, which is not big enough to apply; you can only apply to one of our sandbox projects, see §33 (http://datum.zerocracy.com/pages/policy.html#33)
```
But §33 not exist in the policy.

**Comment by 0crat** [comment]
@yegor256[/z](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.51.4`

**Comment by yegor256** [comment]
@rultor release, tag is `0.51.5`

**Comment by yegor256** [comment]
@fabriciofx should be fine now, see the policy updated

**Comment by 0crat** [comment]
Job [#219](https://github.com/zerocracy/datum/issues/219) was not in scope

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#219` is not assigned, can't get start time
