### ISSUE TITLE
0crat crashed when I opened profile page

### ISSUE THREAD

**Issue by valentjedi** [zerocracy/datum#220]
Can't add any additional info other than my browser is FireFox 57 and I was able to open profile page on the second try. By crash I mean 500 server error.

**Comment by 0crat** [comment]
@yegor256[/z](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@valentjedi most probably we were re-deploying the server side, that's why this 500 page. It's a temporary issue.

**Comment by 0crat** [comment]
Job [#220](https://github.com/zerocracy/datum/issues/220) was not in scope

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#220` is not assigned, can't get start time
