### ISSUE TITLE
0crat does not permit change my rate in a specific project

### ISSUE THREAD

**Issue by fabriciofx** [zerocracy/datum#221]
How can I change my rate in a specific project? I have tried `apply ID $newvalue` but 0crat showed me:
```
Your reputation is 195, which is not big enough to apply; you can only apply to one of our sandbox projects, see §33 (http://datum.zerocracy.com/pages/policy.html#33)
```

**Comment by 0crat** [comment]
@yegor256[/z](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#221](https://github.com/zerocracy/datum/issues/221) assigned to @yegor256[/z](http://www.0crat.com/u/yegor256). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @fabriciofx[/z](http://www.0crat.com/u/fabriciofx), total is [+210](http://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](http://www.0crat.com/u/yegor256), total is [+7390](http://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@fabriciofx fixed

**Comment by 0crat** [comment]
@yegor256[/z](http://www.0crat.com/u/yegor256) resigned from [#221](https://github.com/zerocracy/datum/issues/221), since the job is not in scope anymore

**Comment by 0crat** [comment]
The job [#221](https://github.com/zerocracy/datum/issues/221) is now out of scope

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#221` is not assigned, can't get start time
