### ISSUE TITLE
Reviewer "resigned" from merged PR

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/datum#222]
This [PR](https://github.com/yegor256/cactoos/pull/553#issuecomment-358009717) has been reviewd and merged successfuly, then 0crat says that I (the reviewer) resigned from the job because the job is out of scope.

I am not sure, but from my experience, this is the point where the reviewer is paid since their job is done. **I think the real issue is that 0crat does not make the difference between "out of scope" tasks and "finished" tasks.**

**Comment by 0crat** [comment]
@yegor256[/z](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by iCok** [comment]
Same for me as a developer of issue (https://github.com/yegor256/cactoos/issues/533)

**Comment by iCok** [comment]
It happens for all recently closed PRs at least in Cactoos project. It does not matter what person works

**Comment by t-izbassar** [comment]
+1. [takes#353](https://github.com/yegor256/takes/issues/353)

**Comment by yegor256** [comment]
@amihaiemil it's a bug on our side, thanks for reporting. I will try to fix it now.

**Comment by 0crat** [comment]
Job [#222](https://github.com/zerocracy/datum/issues/222) is now in scope, role is `DEV`

**Comment by yegor256** [comment]
@amihaiemil I think it's fixed... let's keep an eye on it

**Comment by amihaiemil** [comment]
@yegor256 Two PRs were merged and I didn't notice this behaviour. Indeed, it seems to be fixed.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#222` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#222](https://github.com/zerocracy/datum/issues/222) is now out of scope
