### ISSUE TITLE
Why 0crat mentioned me two times?

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/datum#223]
In that comments 0crat is mentioned me two times: [comment](https://github.com/yegor256/cactoos/pull/527#issuecomment-358055120)

What does it mean?

**Comment by 0crat** [comment]
@yegor256[/z](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@t-izbassar it's a typo, fixed, thanks!

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#223` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#223](https://github.com/zerocracy/datum/issues/223) was not in scope
