### ISSUE TITLE
What happens to projects that are not in the board?

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/datum#225]
I was able to join projects that are now not in the board listing. What does this actually means? They are not supported? Can I continue working on them?

**Comment by 0crat** [comment]
@yegor256[/z](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@t-izbassar yes, sure, they are just normal projects. But they don't expect any new members, that's all.
