### ISSUE TITLE
Too much freedom about the rate setting?

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/datum#227]
Apparently, right now I can change my hourly rate any time I want. So I guess it would be possible to agree with Yegor on $10/h, then I get assigned a task of 30min and then I go in my private chat with 0crat and say "my rate is actually $200/h" -- thus, when the task is done, 0crat pays me $100. 

Is this the way it is right now? If so, it doesn't look ok.

**Comment by 0crat** [comment]
@yegor256[/z](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil the rate you set in the chat is your profile rate. It is not the rate you have in a project. Project rate is set only by project PO/ARC. See the difference?

**Comment by amihaiemil** [comment]
@yegor256 In this case, where do I see what a project decided to pay me? I never saw this information anywhere ;)

**Comment by yegor256** [comment]
@amihaiemil you should see it in the project page, for example: http://www.0crat.com/p/C63314D6Z

**Comment by amihaiemil** [comment]
@yegor256 I see. Thanks for explaining :D

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#227` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#227](https://github.com/zerocracy/datum/issues/227) was not in scope

**Comment by amihaiemil** [comment]
@yegor256  I saw you discussed this ticket and said: 

> But would be much better if he would insist that I should have made some changes to the project documentation.

So let's add the following to the documentation, somewhere: 

```
The candidate can change his/her rate by chatting with 0crat at any time. However, that rate is the "market rate", the one proposed to a project when applying. Once the project accepts the candidate, the PO/ARC will set the candidate's "project rate" -- if later, the candidate changes his/her market rate by chatting with 0crat, this will not automatically change the project rates that he/she already has agreed upon earlier. 
```

Also, I noticed that my project rate increased; did you do it manually? is the architect notified when the developers change their profile rate, and he can change the project rate automatically? If you did not change my rate manually, then we have a bug :)

**Comment by 0crat** [comment]
@yegor256[/z](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil I changed it manually) Also, I already updated the policy, check this: http://datum.zerocracy.com/pages/policy.html#16

**Comment by amihaiemil** [comment]
@yegor256 I see, nice :)
