### ISSUE TITLE
Suggestion: Let's add a "agenda" command to 0crat bot

### ISSUE THREAD

**Issue by vmotsak** [zerocracy/datum#230]
To see assigned jobs, with the same functionality as on site.

PS Functionality separation somehow inconvenient seems like site provides the view of the state while bot accepts commands to control it, also something controlled via GitHub comments, which makes you jump back and forth. Another example is board/apply.

**Comment by 0crat** [comment]
@yegor256[/z](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@vmotsak well, we wanted to make the site really static and the bot - dynamic, for commands and control. If we start moving all static information the bot, it will become very big and difficult to use. It's very difficult to render even the agenda there.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#230` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#230](https://github.com/zerocracy/datum/issues/230) was not in scope
