### ISSUE TITLE
0crat not confirming impediment

### ISSUE THREAD

**Issue by llorllale** [zerocracy/datum#235]
It's been over 42 minutes since I [declared](https://github.com/yegor256/jpeek/issues/93#issuecomment-359050643) an impediment for a job and I have yet to see @0crat confirm it.

**Comment by yegor256** [comment]
@llorllale it was a temporary issue, fixed already

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#235` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#235](https://github.com/zerocracy/datum/issues/235) was not in scope
