### ISSUE TITLE
Implements 0crat pause/resume commands

### ISSUE THREAD

**Issue by allanws** [zerocracy/datum#239]
As a Team Member I want to be able to pause/resume getting more work requests so that I can signal the bot to stop/start sending more requests.

Let's suppose one can handle less issues than the bot might flush against, that would be helpful to instruct the bot to stop sending more requests.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@allanws try to use vacation mode: a6ce718

**Comment by allanws** [comment]
That works too, thanks.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#239` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#239](https://github.com/zerocracy/datum/issues/239) was not in scope
