### ISSUE TITLE
0crat.com header list goes out of view on mobile

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/datum#241]
On https://www.0crat.com/, on most pages there is this list of links in the header:

![image](https://user-images.githubusercontent.com/6305156/35267184-25617ad2-002e-11e8-891a-6fd7c19c2a09.png)

On mobile, it goes out of view, it doesn't fit well in the screen's width (I have a 5'' screen). I think on mobile the list should be hidden behind a button similar to this:

![image](https://user-images.githubusercontent.com/6305156/35267258-5909b304-002e-11e8-8809-dbf04f2d8466.png)

This trick is doable with CSS3 I believe. There is an example on my blog, you can see how it's done there.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil this is the problem: https://github.com/yegor256/tacit/pull/142 We'll fix it once tacit is released.

**Comment by amihaiemil** [comment]
@yegor256 Right, then I guess a PR should be made, for this issue, where tacit is updated (once the new version is released)

**Comment by yegor256** [comment]
@amihaiemil yes. would be great if you can submit this issue to the farm repository, that's where the fix will happen: https://github.com/zerocracy/farm

**Comment by amihaiemil** [comment]
@yegor256 done, moved to /farm

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#241` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#241](https://github.com/zerocracy/datum/issues/241) was not in scope
