### ISSUE TITLE
0crat did not close my ticket

### ISSUE THREAD

**Issue by llorllale** [zerocracy/datum#242]
@0crat did not close [this](https://github.com/yegor256/cactoos/issues/63) ticket after the corresponding [PR](https://github.com/yegor256/cactoos/pull/556) was completed.

What happened here?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by amihaiemil** [comment]
@llorllale the author of the ticket has to close it, if he/she is satisfied with the solution. 99% of the cases 1 PR is enough and the author should close the Issue, but there are also times when more PRs are needed -- I don't think this is the case, so just ping the author in that ticket and tell him to close it :) 

Automatic closure of the ticket happens only when 0pdd sees the ticket's puzzle has disappeared from the code,

**Comment by llorllale** [comment]
@amihaiemil I see, thanks!

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#242` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#242](https://github.com/zerocracy/datum/issues/242) was not in scope
