### ISSUE TITLE
Yoti only accepts passports and UK drivers licences

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/datum#243]
I talked with Yoti support and they confirmed that currently they only accept national passports and UK drivers licence. I, for one, would not go through all the husstle of getting a passport just for proving my DOB and name on the Internet and I believe many others think the same. 

On the other hand, I couldn't find any other decent apps, a Google search for "digital identity app" yields only Yoti-related results, so they must be the only decent ones.

**One solution** would be tying the identiy proof to Paypal, since any Paypal user has to submit an ID with photo and has the bank account linked there. Github identity could be tied with PayPal in 2 ways: oblige each contributor to have the same exact name and public email on Github as the name and email of the PayPal account. 

Paypal should be contacted and asked if they can provide the date of birth + location of a user and in what circumstances. I am sure that we are not the first ones with this issue so they must have a process for this.

**The other solution** would be: providing the full name and bank account IBAN, Zerocracy makes a payment there and sends a code in the description. Then, the contributor will find that code on the bank extract and submit it to zerocracy (this is how PayPal validates a new card). 

This way, the name, country and IBAN are proven which I think is enough. Date of birth would be important just to prove that the contributor is of legal age, which we can assume since they have a bank account + Paypal on their name.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#243](https://github.com/zerocracy/datum/issues/243) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+7970](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@amihaiemil see this: b9f08d2c78841fd444d9b7e2d93b6be03e92c1cc

**Comment by amihaiemil** [comment]
@yegor256 thanks :) I sent the email

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8030](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#243](https://github.com/zerocracy/datum/issues/243) is now out of scope

**Comment by llorllale** [comment]
@amihaiemil is your country listed in Yoti's list of [supported passports(https://yoti.zendesk.com/hc/en-us/articles/209348425-What-passports-do-Yoti-currently-support-)?

I'm currently trying to identify myself to Yoti. My country is on that list but for some reason it's not working.

**Comment by amihaiemil** [comment]
@llorllale Yes, it is, but I don't have a passport so I just sent an email directly to Yegor, with my ID (this is for exceptional cases). If your country is listed and your passport is not working, contact their support, they are very responsive.

**Comment by llorllale** [comment]
@amihaiemil @yegor256 FYI it took Yoti 8 days to fix my problem but it's finally working for me
