### ISSUE TITLE
Will zerocrat preserve my tasks assignments for the pause period?

### ISSUE THREAD

**Issue by skapral** [zerocracy/datum#244]
Assume that I pause my account by 0crat `pause`, but still have some tasks assigned on me. What will happen to them? Will they be automatically be `refused` or stayed assigned on me? Both outcomes semantically doesn't contradict paragraph 24: a `pause` may be understood both as "stop giving me new activities" or "I'm on vacation, don't expect anything from me".

IMO it is worth to make this information more explicit.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@skapral see decd3a2 What do you think now?

**Comment by skapral** [comment]
Ups... I mistakenly thought that this command is a pause for a developer, not a project. Sorry.

Speaking of DEV role - does it have some command like `pause`. I rechecked the policy and saw nothing in there. But DEV may probably want to pause his/her activities on vacation or illness period.

**Comment by skapral** [comment]
In the usage of 0crat I saw `vacation` command, but it is not mentioned in the Policy. Worth to mention it there, don't you think? Should I create a separate issue on that?

**Comment by yegor256** [comment]
@skapral This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#244` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#244](https://github.com/zerocracy/datum/issues/244) was not in scope
