### ISSUE TITLE
@0crat status is outdated?

### ISSUE THREAD

**Issue by skapral** [zerocracy/datum#245]
Steps to reproduce.

0. I want to determine which tasks are assigned to me.

1. I opened the policy and saw the following paragraph in there:
> §32 "Job Status." You can always check status of any job, just say status to Zerocrat.

2. I talked to `0crat` in Slack (privately):

```
skapralov [11:39 PM]
@0crat status

0crat APP [11:39 PM]
@skapralov Can't understand "status", try one of these:
 - `apply` Send your profile to the project, intending to join them
 - `hello` Just say hello
 - `invite` Invite a friend
 - `quit` Immediately exit the project
 - `rate` Change your current hourly rate
 - `vacation` Change vacation mode
 - `version` Print current version of the bot
 - `wallet` Change your payment information

Remember, this chat is for managing your personal profile; to manage a project, please open or create a new channel and invite the bot there.
```

3. I checked usage in private Slack and Slack project channel but there is nothing which looks like `status`. Is it outdated? If yes - how can I get a list of jobs assigned on me?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@skapral it's a GitHub command, you can use it in any job ticket.

**Comment by yegor256** [comment]
@skapral see 32eea87

**Comment by 0crat** [comment]
Job [#245](https://github.com/zerocracy/datum/issues/245) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#245](https://github.com/zerocracy/datum/issues/245) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+7945](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@skapral let's close this?

**Comment by skapral** [comment]
Initial problem still remain. My initial intention was to gather a list of jobs assigned on me by 0crat (see step sequence), and I still don't see a way how to do it.

I saw issue #211, which is correlated to the problem. If you are planning to negotiate it there, lets close this one.

**Comment by skapral** [comment]
@yegor256 FYI, forgot to reference you last time

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@skapral you should be able to see your agenda (it's in your account).

**Comment by skapral** [comment]
I see. Looks weird on my favorite Firefox, but it is not the subject of this issue anymore. Closing this issue now.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8905](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#245](https://github.com/zerocracy/datum/issues/245) is now out of scope

**Comment by 0crat** [comment]
Job [#245](https://github.com/zerocracy/datum/issues/245) was not in scope
