### ISSUE TITLE
When does a code review end after I reject the PR and inform the author?

### ISSUE THREAD

**Issue by llorllale** [zerocracy/datum#246]
As per [27](http://datum.zerocracy.com/pages/policy.html#27):
> §27 "Code Reviews." You will be asked to review pull requests if you have REV role assigned. Be as critical as you can, as this article explains. If you accept the changes, inform the architect, right in the ticket. If you don't accept, inform the author of the pull request. In either case you will be paid 15 minutes.

It is not clear to me what needs to happen after I reject the PR and inform the author right in the ticket. There's no mention of what specific words or actions must be taken for a code review to end his job as `REV`. Does `REV` need to close the PR after rejection?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@llorllale see 9aec5bd Better now?

**Comment by llorllale** [comment]
@yegor256 I think it's better. It's shifting the responsibility from the author of the PR (could be anyone) and `REV`, over to `ARC`, who also has an incentive to close the job.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#246` is not assigned, can't get start time

**Comment by llorllale** [comment]
Reopened because that commit is not yet merged.

**Comment by llorllale** [comment]
@yegor256 to be clear, this means that after `REV` informs `ARC` of GREEN/RED decision, `ARC` must then either merge the PR or close it, and nothing in between, right?

**Comment by 0crat** [comment]
Job [#246](https://github.com/zerocracy/datum/issues/246) was not in scope

**Comment by yegor256** [comment]
@llorllale yes, that's correct

**Comment by yegor256** [comment]
@rultor release, tag is `0.52.3`

**Comment by yegor256** [comment]
@llorllale check the current version of policy: http://datum.zerocracy.com/pages/policy.html

**Comment by llorllale** [comment]
@yegor256 looks good

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#246` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#246](https://github.com/zerocracy/datum/issues/246) was not in scope
