### ISSUE TITLE
Multiple reviewers allowed now?

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/datum#247]
It happened a number of times so far, the architect assigned me to do a review of a PR which had already been reviewed by someone else (also working for ZC, 0crat had assigned them). For instance, https://github.com/yegor256/cactoos/pull/516 has been reviewed and sent to the architect. It was the architect's turn to do a final review and accept the PR. 

What happens if I review it as well and the PR gets merged? Will the initial reviewer be paid as well? Do we allow multiple reviews now?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@amihaiemil it was just a mistake. We always do two reviews: one `REV` and one `ARC`.

**Comment by 0crat** [comment]
The job [#247](https://github.com/zerocracy/datum/issues/247) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8085](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8115](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#247](https://github.com/zerocracy/datum/issues/247) is now out of scope
