### ISSUE TITLE
More respect for contribution to the projects from people who are not applied into?

### ISSUE THREAD

**Issue by skapral** [zerocracy/datum#248]
Example. I am not a member of 0crat project. As a non-member, I can't be assigned on issues there, and it's fair.

However, I am a user of 0crat, I use it every day, face bugs, issues, unndocumented behavior and create tickets for them. It is my small but fair contribution to it. So far, I haven't seen that my issues were declined. If I was a member, I would be rewarded by points for each issue. But I am not, which makes me much less motivated to contribute there.

Is it possible for 0crat to reward with points the originator of a bug, if he/she is member of 0crat gang, but not the member of the project the bug is created in?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@skapral I agree, we should give points, if the reporter is a member of our gang

**Comment by 0crat** [comment]
Job [#248](https://github.com/zerocracy/datum/issues/248) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#248](https://github.com/zerocracy/datum/issues/248) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/511200185). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@skapral PR zerocracy/farm#641 was merged, can we close?

**Comment by skapral** [comment]
@g4s8 ok.

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8), total is [+4765](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#248](https://github.com/zerocracy/datum/issues/248) is now out of scope
