### ISSUE TITLE
0crat still warning about Ten Days Rule even while job has impediment

### ISSUE THREAD

**Issue by llorllale** [zerocracy/datum#249]
Is this by design or a bug? For example, see [here](https://github.com/yegor256/jpeek/issues/93).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@llorllale it was a bug, fixed already

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#249` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#249](https://github.com/zerocracy/datum/issues/249) was not in scope
