### ISSUE TITLE
0crat + 0pdd: is it possible to place impediments referencing 0crat in puzzles?

### ISSUE THREAD

**Issue by skapral** [zerocracy/datum#251]
Assume I have a puzzle. I know that the puzzle depends on some GitHub issue. Can I use 0pdd this way, expecting that once the puzzle will be merged into upstream and the issue created by 0pdd, 0crat will notice that and place impediment on issue 107:
```
            /*
            @todo #9:30min Cover these metrics with auto-tests and uncomment these lines

             @0crat waiting #107

             new Report(skeleton, "TCC",  this.params, 0.5d, 0.25d),
             new Report(skeleton, "LCC",  this.params, 0.5d, 0.25d)
            */
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@skapral I like the idea, but it seems that a bit "intrusive". Not every ticket must wait if a puzzle is introduced. It's more a decision of a programmer. I don't think we should let our software make that kind of decision automatically.

**Comment by skapral** [comment]
@yegor256 Sounds reasonable to me. If 0crat indeed doesn't let 0pdd user to interfere and set impediments, I am ok to closing this issue.

**Comment by yegor256** [comment]
@skapral they don't interfere anyhow

**Comment by skapral** [comment]
@yegor256 Lets close it then?

**Comment by yegor256** [comment]
@skapral it's your ticket :) Please, close

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#251` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#251](https://github.com/zerocracy/datum/issues/251) was not in scope
