### ISSUE TITLE
Does quit affect my points?

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/datum#254]
The question is: if I quit do I get penalties? What if I have unfinished tasks. They will be refused and I get `-15` for everyone?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@t-izbassar when you quit, you will stop getting new tasks in the project and will stop making points from reporting bugs. But you will still have to finish the tasks you have. If you don't, there will be penalties.

**Comment by yegor256** [comment]
@t-izbassar see f82432c

**Comment by t-izbassar** [comment]
@yegor256 OK for me. Thanks.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#254` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#254](https://github.com/zerocracy/datum/issues/254) was not in scope

**Comment by yegor256** [comment]
@rultor release, tag is `0.53.2`
