### ISSUE TITLE
Java test of XSL stylesheet

### ISSUE THREAD

**Issue by yegor256** [zerocracy/datum#255]
Look at https://github.com/zerocracy/farm/issues/468

It seems that the testing we are doing in Ruby is not strong enough. We should validate our XSL stylesheets in Java somehow. Let's create a simple Java command line sub-project inside this one (Maven + pom + Main.java + Saxon + jcabi-xml), which will open all `.xsl` files and validate them against `simple.xml` files, just like our `xsl` goal in `Rakefile` is doing.

**Comment by 0crat** [comment]
Job [#255](https://github.com/zerocracy/datum/issues/255) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+8345](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Job [#255](https://github.com/zerocracy/datum/issues/255) is already in scope

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat waiting #284

**Comment by 0crat** [comment]
> @0crat waiting #284  ([here](https://github.com/zerocracy/datum/issues/255#issuecomment-368331150))

@g4s8 The impediment for [#255](https://github.com/zerocracy/datum/issues/255) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@yegor256 PR #284 was merged and todos #310, #311 were submited. Can we close?

**Comment by g4s8** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#255](https://github.com/zerocracy/datum/issues/255) is now out of scope

**Comment by ypshenychka** [comment]
@g4s8 According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All impediments registered in the ticket have explanations of the reasons and links to related tickets, if necessary.

Please add more details to registered [impediment](https://github.com/zerocracy/datum/issues/255#issuecomment-368331150).

**Comment by g4s8** [comment]
@ypshenychka fixed, please look again

**Comment by ypshenychka** [comment]
@g4s8 thank you

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by yegor256** [comment]
@g4s8 I decided to do it in a much simpler way, see: 7c6f8f4

**Comment by 0pdd** [comment]
@yegor256 all 2 puzzles are solved here: [#310](https://github.com/zerocracy/datum/issues/310), [#311](https://github.com/zerocracy/datum/issues/311).
