### ISSUE TITLE
Tell the rate when you get approved to project by PO

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/datum#256]
From telegram bot when I have applied to project I get:
> You just got role DEV in C3FFK3YAY

I think it will be useful to inform about rate that was established within that project to get:
> You just got role DEV in C3FFK3YAY with $10 rate

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@t-izbassar done in https://github.com/zerocracy/farm/commit/bab2228298f50d7923fc2387590549aa64f54571, thanks for suggesting!

**Comment by 0crat** [comment]
Job [#256](https://github.com/zerocracy/datum/issues/256) was not in scope

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#256` is not assigned, can't get start time
