### ISSUE TITLE
Allow to set max available jobs

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/datum#258]
For example I have high rating but I want to slow down a bit, but I don't want to go on vacation mode. Just get less jobs for certain period of time. So I want to limit jobs assignments from zerocrat.

Proposition is to add command `job set 10` or something like that so that I can limit jobs. Value should be less than max allowed tasks.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#258](https://github.com/zerocracy/datum/issues/258) is now in scope, role is `DEV`

**Comment by yegor256** [comment]
@g4s8 @carlosmiranda I'm thinking about creating a new artifact per user, like `options/yegor256.xml`, in PMO. This artifact will contain configuration parameters, which a user will be able to change by just uploading a new version of the file to us, via the web front. What do you think?

**Comment by t-izbassar** [comment]
@yegor256 I think that's good idea. Possible values can include:
- wallet
- jobs limit
- PRs to review limit
- rate
- vacation
- preferable role

There also can be values for other roles but I'm not aware of them.

**Comment by t-izbassar** [comment]
And also having editing one file seems more easy way than having different bot commands where you need to remember semantics and allowed commands. Xml will be more transparent.

**Comment by g4s8** [comment]
@yegor256 I think it may include notification preferences, e.g. I'd prefer to receive notifications in Telegram only.

**Comment by 0crat** [comment]
The job [#258](https://github.com/zerocracy/datum/issues/258) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/511619587). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/zerocracy/datum/issues/258#issuecomment-369849159))

@g4s8 The impediment for [#258](https://github.com/zerocracy/datum/issues/258) was registered successfully by @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@t-izbassar PR's #309 and zerocracy/farm#693 were merged,`@ todo` #820 was submitted, can we close then?

**Comment by t-izbassar** [comment]
@g4s8 sure. Thanks.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @g4s8[/z](https://www.0crat.com/u/g4s8), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#258](https://github.com/zerocracy/datum/issues/258) is now out of scope

**Comment by ypshenychka** [comment]
@t-izbassar According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Messages in a job [always](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noiseaddress-your-comments) start with a name of a user they are addressed to.

Please correct your [message](https://github.com/zerocracy/datum/issues/258#issuecomment-361629540) by indicating an addressee in the beginning.

**Comment by ypshenychka** [comment]
@g4s8 According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>All impediments registered in the ticket have explanations of the reasons and links to related tickets, if necessary.

Please add more details on the registered [impediment](https://github.com/zerocracy/datum/issues/258#issuecomment-369849159)

**Comment by g4s8** [comment]
@ypshenychka sure, changed comment

**Comment by ypshenychka** [comment]
@g4s8 Thank you!

**Comment by t-izbassar** [comment]
@ypshenychka 
> Please correct your message by indicating an addressee in the beginning.

Done. However, shouldn't it be addressed to job performer? As issue reporter not interested in the ticket as long as it is already closed. But feel free to ignore this remark.

**Comment by ypshenychka** [comment]
@t-izbassar It's in job performer's interest to ask you to make this change prior to QA review.

**Comment by ypshenychka** [comment]
@t-izbassar Thank you!

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
