### ISSUE TITLE
Occasionally 0crat responds inadequately on status request

### ISSUE THREAD

**Issue by skapral** [zerocracy/datum#260]
0crat sometimes responds with the following message on `@crat status`:

> Are you speaking to me or about me here. You must always start your message with my name if you want to address it to me, see §1.

See here:
https://github.com/yegor256/jpeek/issues/17,
https://github.com/yegor256/jpeek/issues/15

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#260](https://github.com/zerocracy/datum/issues/260) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#260](https://github.com/zerocracy/datum/issues/260) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/511157067). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by g4s8** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/datum/issues/260#issuecomment-369848965))

@g4s8 The user @g4s8[/z](https://www.0crat.com/u/g4s8) resigned from [#260](https://github.com/zerocracy/datum/issues/260), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#260](https://github.com/zerocracy/datum/issues/260) assigned to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/620808853). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by amihaiemil** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/zerocracy/datum/issues/260#issuecomment-370339957))

@amihaiemil The impediment for [#260](https://github.com/zerocracy/datum/issues/260) was registered successfully by @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by amihaiemil** [comment]
@skapral PR for this has been merged, please close this. I simplified the logic (no more regex) and wrote unit tests. All should be fine now.

**Comment by skapral** [comment]
Ok

**Comment by amihaiemil** [comment]
@skapral please address the comment to me (the QA will probably ask you, anyway) :)

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by amihaiemil** [comment]
@skapral ping, pls edit that comment

**Comment by skapral** [comment]
@amihaiemil Done I hope -_\

**Comment by ypshenychka** [comment]
@amihaiemil According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Some of ticket messages must mention all pull requests where the problem was actually fixed.

Please provide a link to corresponding PR in any of your messages.

**Comment by amihaiemil** [comment]
@ypshenychka right, here is the PR: https://github.com/zerocracy/farm/pull/720

**Comment by ypshenychka** [comment]
@amihaiemil thank you

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/zerocracy/datum/issues/260#issuecomment-370828537). You must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1).

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/zerocracy/datum/issues/260#issuecomment-370828608))

@ypshenychka You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `QA`.

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/zerocracy/datum/issues/260#issuecomment-370828608))

@ypshenychka The job [#260](https://github.com/zerocracy/datum/issues/260) is now out of scope
