### ISSUE TITLE
0crat assigns already merged pull request to review

### ISSUE THREAD

**Issue by skapral** [zerocracy/datum#261]
Check PR https://github.com/yegor256/jpeek/pull/108. It is definitely not a QA, because the message is referencing a paragraph from code review section:

> This pull request #108 is assigned to @carlosmiranda/z. The budget is 15 minutes, see §4. Please, read §27 and when you decide to accept the changes, inform @yegor256/z (the architect) right in this ticket. If you decide that this PR should not be accepted ever, also inform the architect.

**Comment by skapral** [comment]
It was a duplicate. Sorry: https://github.com/zerocracy/farm/issues/487

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#261` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#261](https://github.com/zerocracy/datum/issues/261) was not in scope
