### ISSUE TITLE
Llink to `Gang` page should be on all pages of 0crat site

### ISSUE THREAD

**Issue by neonailol** [zerocracy/datum#267]
Right now link to the `Gang` page exists only on `Policy` page

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@neonailol it exists in all pages, but either on top of the screen, or at the bottom.

**Comment by neonailol** [comment]
@yegor256 oh, i see now :) i never bothered to scroll down and look at footer

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#267` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#267](https://github.com/zerocracy/datum/issues/267) was not in scope
