### ISSUE TITLE
What is mentor responsibilites?

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/datum#269]
I think there should be clarification of what should mentor do. For example I have @yegor256 as my mentor. It's great to have him for me) however, what does it mean? Can I go to him and ask questions? Should he comment on my solutions to improve? Review PRs? What's hes role for me so that he gets bonuses for my positive move and fines for negative move? For now, it is just a mentioning on gang page. 

Also from my perspective it's not obvious. For example with what questions I can go to my mentor? Or can I even do that? What is my obligations to him?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@t-izbassar you should be able to do anything you want. This person is making money out of your activity, of course, he/she will be interested to talk to you. I don't see what can we say in the Policy about it. Also, I will not be a mentor very soon, since it's too much work/hassle for me.

**Comment by t-izbassar** [comment]
@yegor256 got it, makes sense. I think the only things that should be mentioned is what mentor gets and what he loses and from what point he can become a mentor. But that's should be mentioned when relevant tasks are implemented.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#269` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#269](https://github.com/zerocracy/datum/issues/269) was not in scope
