### ISSUE TITLE
Acceptance criteria

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/datum#270]
I think we should have clear acceptance criteria to become `Gang` member. For now people are asking, what should I have to do, what knowledge is enough, what experience is enough and so on.

I know that we are not strictly care about the whole CV process and things like that because as long as member delivers results he will be paid and will grow reputation. But do we want noise from complete novice guys? And it will be easier if we have check-list for mentors to filter because the member's performance that he invited will affect his reputation as well. Maybe give that check-list as recommendation, and the decision invite or not invite will be completely on mentor's responsibility.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#270](https://github.com/zerocracy/datum/issues/270) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#270](https://github.com/zerocracy/datum/issues/270) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9360](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by yegor256** [comment]
@t-izbassar we will solve it there: https://github.com/zerocracy/farm/issues/520

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9750](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#270](https://github.com/zerocracy/datum/issues/270) is now out of scope
