### ISSUE TITLE
0crat assigning closed issue

### ISSUE THREAD

**Issue by llorllale** [zerocracy/datum#272]
0crat just assigned an issue that I completed a few hours ago [here](https://github.com/yegor256/jpeek/issues/104#issuecomment-363590759)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@llorllale please, report it to the "farm" repository. "Datum" is for policy questions.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#272` is not assigned, can't get start time

**Comment by llorllale** [comment]
Got it, thanks

**Comment by 0crat** [comment]
Job [#272](https://github.com/zerocracy/datum/issues/272) was not in scope
