### ISSUE TITLE
Receive tasks after vacation ended

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/datum#273]
I'm not receiving tasks since my vacation was ended. My vacation started February 2 and ended February 5. So for two days I'm not receiving any tasks having in agenda only 1 job left (max available is 3).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by t-izbassar** [comment]
Hi @yegor256 can you please check it out? I have some free time and it's unfortunate that I'm not receiving tasks.

**Comment by yegor256** [comment]
@t-izbassar I don't think it's true. I'm sure it's not true. Most probably Zerocrat just doesn't elect you, for some reason. From now on, you will see the reasons in each task and will understand what's going on.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#273` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#273](https://github.com/zerocracy/datum/issues/273) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/401206017) The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9505](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9535](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#273](https://github.com/zerocracy/datum/issues/273) is now out of scope

**Comment by 0crat** [comment]
Job [#273](https://github.com/zerocracy/datum/issues/273) was not in scope

**Comment by t-izbassar** [comment]
@yegor256 I still doesn't get why I'm not elected. There are jobs in Takes for example, where I have positive points. And so I need to go into each issue and see the reasons? That's very tedious job to do. Or how else I can see why I'm not elected?
