### ISSUE TITLE
0crat commands are broken when I change github username

### ISSUE THREAD

**Issue by nick318** [zerocracy/datum#274]
Ocrat commands do not work when a user change github username. You can see it in an issue https://github.com/yegor256/cactoos/issues/585

Steps to reproduce:
1 A task assigned to user with nickname `icok`
2 The user changes github name to `nick318`
3 The user type a command `@Ocrat refuse`
4 The answer is `You need to ask somebody to invite you: https://github.com/zerocracy/datum#invite-only`

I suppose to have a way of updating github username in order to get back on track with `0crat` commands.

@yegor256 WDYT?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@nick318 how can you "change" github name? AFAIK it's impossible. You can only register a new account. Or I'm wrong?

**Comment by nick318** [comment]
@yegor256 you are wrong. Read here: https://help.github.com/articles/changing-your-github-username/

**Comment by nick318** [comment]
@yegor256 It seems I am not alone who changed username.

**Comment by yegor256** [comment]
@nick318 I guess you will have to create your account from scratch. I can't invent a procedure how we can transfer one account to another. We simply can't automatically verify that the previous account really belongs to you. So, start from scratch with us and create a new account.

**Comment by nick318** [comment]
@yegor256 Got it, thank you.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#274` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#274](https://github.com/zerocracy/datum/issues/274) was not in scope
