### ISSUE TITLE
Why I'm not beign elected?

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/datum#275]
I'm not receiving task for about a weak now. I have [positive points](https://www.0crat.com/u/t-izbassar/awards), I'm member of [Takes](https://www.0crat.com/p/C3FFK3YAY) which obviously have [jobs in scope](https://github.com/yegor256/takes/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Ascope) and it is alive project. According to [policy](http://datum.zerocracy.com/pages/policy.html#3) I should win election. So why I'm not receiving jobs?

Where to look for a reason to see why I'm not receiving jobs in that project? For example, I'm also have role DEV in [Cactoos](https://www.0crat.com/p/C63314D6Z) but I can only speculate on the reasons why I'm not receiving jobs. 0crat gives no hints on that, neither it is mentioned in the profile page. I don't want to go and check every issue to find out that it is dispatched to others.

So what should I do? Where to look for a reasons? I though it was related to #273 but it's not as far as I can imagine.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by t-izbassar** [comment]
@yegor256 I received task) however, it was not obvious, why I wasn't receiving it for quite some time. Don't sure what should be done to help others in same situation. Maybe, just nothing)

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#275` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#275](https://github.com/zerocracy/datum/issues/275) was not in scope

**Comment by yegor256** [comment]
@t-izbassar the project was not "funded", that's why nobody was receiving tasks.

**Comment by t-izbassar** [comment]
@yegor256 do you think there should be notification to members about that? So that they will move to other projects?

**Comment by yegor256** [comment]
@t-izbassar you are right, this information will be visible in the board: https://github.com/zerocracy/farm/commit/56455b6f12d9d054a80e047a2d95c25b2bee2f06

**Comment by t-izbassar** [comment]
@yegor256 what about invisible projects that are not listed on the board?

**Comment by yegor256** [comment]
@t-izbassar well, I guess it's against our philosophy. You, as a programmer, should not care about project situation. They don't guarantee you anything. They may have tasks and the next day there are no tasks. You should not worry about it. If you are not elected, just check the recent tickets assigned and see why their performers were assigned. That's all we can do. We should not disclose too much project information to developers, I believe.
