### ISSUE TITLE
Typo in word "Zerocray" in Policy document §36 "Speed Bonus."

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/datum#278]
STR:
1. Go to http://datum.zerocracy.com/pages/policy.html#36
2. Observe the first sentence

**Actual Result**: Typo in word "Zerocray"

![image](https://user-images.githubusercontent.com/11703257/36229684-c01e7a8e-11e0-11e8-94fd-6f422bc8066e.png)

**Expected Result:** "...Zerocracy measures the time interval between the moment a job is assigned to you and the moment it goes out of scope..."

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#278](https://github.com/zerocracy/datum/issues/278) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/452232130). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by yegor256** [comment]
@ypshenychka fixed, thanks

**Comment by yegor256** [comment]
@rultor release, tag is `0.54.2`

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9764](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@ypshenychka thanks for reporting this. Next time, for cosmetic issues like this, you can just submit a pull request directly to the files in this repo: https://github.com/zerocracy/datum/blob/master/md/policy.md

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9794](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#278](https://github.com/zerocracy/datum/issues/278) is now out of scope
