### ISSUE TITLE
Redundant word "can" in Policy document §40 "Reply to RFP."

### ISSUE THREAD

**Issue by ypshenychka** [zerocracy/datum#279]
STR:
1. Go to http://datum.zerocracy.com/pages/policy.html#40
2. Observe the second sentence

**Actual Result:** Redundant word "can"
![image](https://user-images.githubusercontent.com/11703257/36229912-6a4a2c74-11e1-11e8-89e9-be16f727b0e8.png)

**Expected Result:** "...You can "pay" 256 points for an email address of any RFP..."

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@ypshenychka fixed, thanks!

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#279` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#279](https://github.com/zerocracy/datum/issues/279) was not in scope

**Comment by ypshenychka** [comment]
@yegor256 Looks like it's not fixed in document.

**Comment by ypshenychka** [comment]
@yegor256 Changes are not merged.

**Comment by yegor256** [comment]
@ypshenychka please refresh the page, should be fine now: http://datum.zerocracy.com/pages/policy.html

**Comment by ypshenychka** [comment]
@yegor256 Fixed. Thanks
