### ISSUE TITLE
Is it ok to have a qa review after PR is already merged?

### ISSUE THREAD

**Issue by nick318** [zerocracy/datum#280]
Here is my [PR](https://github.com/yegor256/cactoos/pull/649) which was merged, after that one user was assigned as a QA, is it a right way to check my PR after it was merged?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by amihaiemil** [comment]
@nick318 As I understand, in the case of a PR the QA checks the quality of the CR's job not the author's. It doesn't affect your payment since you are paid based on the closed ticket, not on the merged PR. Makes sense? @yegor256 correct me if I'm wrong, pls

**Comment by yegor256** [comment]
@amihaiemil yes, totally correct
