### ISSUE TITLE
QA review on issues should be limited to the activities of current job performers

### ISSUE THREAD

**Issue by llorllale** [zerocracy/datum#290]
**Problem**
QA reviews are being delayed because of messages left by users other than the current job performer. Example [here](https://github.com/yegor256/jpeek/issues/67). 

[This](https://github.com/yegor256/jpeek/issues/8) other issue hasn't reached QA yet, but it has un-addressed messages from non-zerocrats posted *months* ago.

**Suggestion**
QA reviews should limit themselves to the activities of the currently assigned job performers, not traces of past activities done by other people. 

I know as `DEV` I have the option to upfront `refuse` a task but:
* I'll be penalized -15 points
* It does not move the project along

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@llorllale the quality of the job will just be "acceptable" instead of "good", that's all. We can't "forgive" anything in the ticket, the quality is the quality.
