### ISSUE TITLE
The DEV should not be responsible for quality of the issue description

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/datum#296]
According to policy rules there are rules that talking about job description. But job description is what the issue reporter is doing, not the `DEV`. But if issue is not defined well - 0crat will punish the `DEV` for that (if QA will say that quality is bad), not the issue reporter and not the `ARC` or `PO` who approved issue as bug.

I don't see logic behind that. I'm just happen to be a `DEV` assigned to the task. Why I am who punished who the low quality of the issue itself?

I expect that `ARC` should be punished who accepting those kind of issues. When issue come up to `DEV` it should be already well defined and specific. Also, the issue reporter should be punished, if `ARC` rejects the issue and `ARC` should be rewarded (+5) for that action. As he is wasting time to read the issue and to understand whether it makes sense or not.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@t-izbassar you should not start working with the job, if the description is not correct. Just demand the author of the ticket to formulate it correctly.
