### ISSUE TITLE
RFP telegram message vs. actual page is confusing

### ISSUE THREAD

**Issue by filfreire** [zerocracy/datum#299]
Today I got two similar messages stating that an RFP was published and I can join as an architect, like the screenshot below:
<img width="387" alt="screen shot 2018-02-22 at 23 57 39" src="https://user-images.githubusercontent.com/11976836/36570917-39798c10-182c-11e8-9812-24693cfb7a03.png">

When I clicked on the `join` link, I was taken to this page:
<img width="445" alt="screen shot 2018-02-22 at 23 57 11" src="https://user-images.githubusercontent.com/11976836/36570918-3995ed1a-182c-11e8-891a-8b22db0c5c69.png">

- Why do the messages say that I can join, because of having a reputation over 512, but once on the website I see that after all, I can't join because my reputation of 525 is not big enough?

- Why did I receive 2 messages with basically the same content instead of just 1 message with all the info I'd need?

- What does RFP mean? Plus, As a user of 0crat, I could have a quick way (example: a link to the policy) explaining what RFP means.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@filfreire it was a bug, already fixed in https://github.com/zerocracy/farm/issues/628 Thanks.
