### ISSUE TITLE
QA rule - the impediment request should clarify what exactly the impediment is

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/datum#300]
When `DEV` or `CR` request for the impediment - it is slowing down the whole process. The fact is that to register impediment you don't need to clarify what exactly you are waiting for. I feel like this decreases the quality, as it is not clear what are the dependencies between tasks and in which order they should be finished.

Thus, there should be a QA rule that sounds something like this:
> Impediment registered in the ticket has clear link on connected issues.

**Comment by yegor256** [comment]
@t-izbassar sounds right. In the future, please report policy changes/bugs to this repo: https://github.com/zerocracy/zerocracy.github.io

**Comment by yegor256** [comment]
@t-izbassar fixed here: https://github.com/zerocracy/zerocracy.github.io/commit/31334447eabfcba64b770d54417f49d93618140
