### ISSUE TITLE
QA should not wait for response of the performer

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/datum#301]
I noticed this behavior from QA: QA reviewing the task, found some rules violated. QA adds the comments with violated rules and await the confirmation of them from the task performers. See [here](https://github.com/yegor256/jpeek/pull/179) or [here](https://github.com/yegor256/takes/pull/803).

I feel like this is just time wasting. Why QA needs task performance approval? Just mention what is violated and give the verdict. That's it. As a result, in mentioned above PR for example CR was resigned from the task as time has passed. It's already 10 day rule applicable for waiting different things to happen. Adding to that those confirmations seems redundant.

In the policy there should be mentioned how to do the verdict and there should be no waiting for some approvals from task performers.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by llorllale** [comment]
@t-izbassar I think the goal is to try to guarantee the quality of a project's documentation and not so much about reviewing the quality of job performers themselves.

**Comment by yegor256** [comment]
@t-izbassar the goal is to punish the performer with this extra waiting time. Next time you will think twice whether to follow the rules or not. The same happens with road police inspectors. They take a lot of time to give you a ticket, moving very slowly, in order to give you extra punishment :)

**Comment by t-izbassar** [comment]
@yegor256 nice)
