### ISSUE TITLE
Review job is not assigned to anyone

### ISSUE THREAD

**Issue by nick318** [zerocracy/datum#306]
**The problem:** 
For a few days is no assignee for a pull request
List of mentioned PR:
https://github.com/yegor256/cactoos/pull/713
https://github.com/yegor256/cactoos/pull/717
https://github.com/yegor256/cactoos/pull/716

**Expected:**
0crat assignees the PR to somebody

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by t-izbassar** [comment]
@nick318 check the status of the project at the board. Cactoos seem to have problems with funds, that's why no tasks will be assigned.

**Comment by nick318** [comment]
@t-izbassar got it, thank you
