### ISSUE TITLE
0crat assignes closed issues

### ISSUE THREAD

**Issue by flslkxtc** [zerocracy/datum#307]
All 3 of my current jobs were assigned to me after they were successfully closed.
Here's links to those assignments: 
- https://github.com/yegor256/cactoos/issues/646#issuecomment-369334408
- https://github.com/yegor256/cactoos/issues/648#issuecomment-369335455
- https://github.com/yegor256/cactoos/issues/641#issuecomment-366071116

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by nick318** [comment]
@yegor256 same here https://github.com/yegor256/cactoos/issues/636

**Comment by yegor256** [comment]
@flslkxtc fixed, thanks. It's a dup of #658
