### ISSUE TITLE
Remove rule "waiting period" on DEV after QA has started review on a DEV ticket

### ISSUE THREAD

**Issue by llorllale** [zerocracy/datum#308]
**Problems**
* DEV's work (the PR) is merged but the waiting period expires while QA review is in progress. DEV is resigned from the job without warning (see DEV job [here](https://github.com/yegor256/jpeek/issues/8) and relevant PR [here](https://github.com/yegor256/jpeek/pull/206). I think this is a pretty serious issue.
* 0crat failed to warn DEV about the impending timeout

**Proposal**
After QA review begins, the "waiting period" should apply to the QA, not the DEV.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@llorllale we can't do that. The rule is strict: 0/100. While the job is yours, it's yours. Who is making you troubles -- it's your problem. We don't touch you until the job is done and closed. Either the QA is not answering, or even if Zerocrat is not answering, doesn't matter. It's either done or not and it's **only your** responsibility. See http://www.zerocracy.com/policy.html#7

Also, read this: http://www.yegor256.com/2014/04/13/no-obligations-principle.html

I understand that it sounds harsh and unusual, but this is how proper management should be done. Everything else leads to problems.

**Comment by llorllale** [comment]
@yegor256 
Someone with a wider scope than `DEV` needs to be incentivized somehow to ensure a "smooth" workflow. Either with punishments or rewards.

Years ago when I first started working as a corporate slave and was young and more stupid, I felt the misguided need to keep pushing all my dependencies in order to get my job done ("QA what's taking so long?!", "PO please answer my doubts!", "release engineer have you approved my changes?!?!?" etc etc.). **It sucks and leads to burnout.** 

I feel the policy is pushing `DEV` in that direction. It is wasteful of a developer's time to have to run around pushing other people to do their jobs in the pipeline. It is also wasteful of a developer's time to have to keep track of how many days left until timeout *in case 0crat is down and/or fails to warn about impending timeout*.

As it is *today*, this 0/100 rule may work for the PM but it is adding a lot of maintenance burden on the DEV.
