### ISSUE TITLE
App.java:28-30: App is not implemented. It should parse...

### ISSUE THREAD

**Issue by 0pdd** [zerocracy/datum#310]
The puzzle `255-3767036a` from #255 has to be resolved:

https://github.com/zerocracy/datum/blob/ea9c8b7026d921dea2af7c229cfeb54064c2f8f7/validator/src/main/java/com.zerocracy.validator/App.java#L28-L30

The puzzle was created by g4s8 on 17-Feb-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#310](https://github.com/zerocracy/datum/issues/310) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `255-3767036a` has disappeared from the source code, that's why I closed this issue.
