### ISSUE TITLE
QA is blocking on the feedback from lost job performer

### ISSUE THREAD

**Issue by skapral** [zerocracy/datum#317]
First mentioned here: https://github.com/zerocracy/datum/issues/264#issuecomment-370793572
Consequences may be seen here: https://github.com/yegor256/jpeek/pull/179

Quote from policy, paragraph [42](http://www.zerocracy.com/policy.html#42)
> When you find any rules violation, ask job performer to confirm that your complains are understood and he/she will try to avoid those mistakes in the future. Until you get a confirmation, don’t give any quality mark.

This note in policy could cause unsolvable situations from QA point of view: since the PR and issue are closed and job performers doesn't have any more interest to maintain the task, QA may be blocked on them, waiting for the feedback.

Proposal is one of the following:

1. Either let QA review the opened task after the ARC and give the remarks like any other reviewer.

2. Or don't require the QA to wait for any confirmation from job participants: just let them pull the good/bad quality trigger and cause consequences for them. Like an independent arbiter. It's their fault that they didn't found the quality issues on review.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@skapral but QA is interested in closing the task (in order to get the money). The QA won't wait for too long. Or I missed the point?

**Comment by skapral** [comment]
@yegor256 they _must_ wait, doesn't they?

> Until you get a confirmation, don’t give any quality mark.

**Comment by yegor256** [comment]
@skapral you are right, see: https://github.com/zerocracy/zerocracy.github.io/commit/f03797621607de9b137f32d520a6d4dab86778d4

**Comment by skapral** [comment]
@yegor256  I'd make it even more permissive. "Don't wait for anybody, just make a verdict on what you got and call it a day". But ok, this suits too. Should I close the issue?

**Comment by yegor256** [comment]
@skapral yes, please close

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
