### ISSUE TITLE
Vacation mode for slack does not work

### ISSUE THREAD

**Issue by nick318** [zerocracy/datum#328]
Vacation mode for slack does not work
Steps:
1 Write to slack bot:
vacation on

Actual Result:
Can't understand "on", try one of these:
Expected:
vacation mode is on

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@nick318 fixed in https://github.com/zerocracy/farm/commit/bf53d085c7f51f3bc13e2b416c10a6cdcd557773
