### ISSUE TITLE
add QA tasks to agenda

### ISSUE THREAD

**Issue by yegor256** [zerocracy/datum#330]
Let's add quality review jobs to the agenda of QA. Also, let's remove them from the agenda, when quality verdicts are given.

**Comment by yegor256** [comment]
@0crat assign @carlosmiranda

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/datum/issues/330#issuecomment-373500756))

@yegor256 Job `gh:zerocracy/datum#330` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat assign @carlosmiranda  ([here](https://github.com/zerocracy/datum/issues/330#issuecomment-373500650))

@yegor256 The job [#330](https://github.com/zerocracy/datum/issues/330) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/742025039). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by carlosmiranda** [comment]
@yegor256 this is also in https://github.com/zerocracy/farm/issues/822, should I use that ticket instead?

**Comment by carlosmiranda** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@carlosmiranda you are right, it's a duplicate

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/datum/issues/330#issuecomment-374520367))

@yegor256 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#330](https://github.com/zerocracy/datum/issues/330) is [in scope](http://www.zerocracy.com/policy.html#14) for 5days
  * The role is `DEV`
  * The job is assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) for [5days](http://www.zerocracy.com/policy.html#8)
  * There is a monetary reward attached
  * @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) will get 50% of their hourly rate for this job
  * Some equity will be [vested](http://www.zerocracy.com/policy.html#37) on completion
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Fdatum%23330%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#330](https://github.com/zerocracy/datum/issues/330), please stop working. Reason for job resignation: GitHub issue was closed as INVALID

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/datum/issues/330#issuecomment-374524688))

@yegor256 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#330](https://github.com/zerocracy/datum/issues/330) is [in scope](http://www.zerocracy.com/policy.html#14) for 5days
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
    * @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Fdatum%23330%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/zerocracy/datum/issues/330#issuecomment-374525868))

@yegor256 The job [#330](https://github.com/zerocracy/datum/issues/330) is now out of scope
