### ISSUE TITLE
Date template is not accurate

### ISSUE THREAD

**Issue by g4s8** [zerocracy/datum#336]
`date` template in `templates.xsl` is not accurate because it calculates one month as 30 days, regardless of what is the month:
```xsl
<xsl:value-of select="$minute + $hour * 60 + $day * 60 * 24 + $month * 60 * 24 * 30 + $year * 60 * 24 * 365"/>
```
it produces incorrect values in agenda: https://github.com/zerocracy/farm/issues/683

To reproduce it just change `added` values in `agenda/simple` to:
```xml
<added>2018-02-27T12:00:00.684Z</added>
```
and `today` param in `templates.xsl` to:
```xsl
<xsl:param name="today" select="'2018-03-01T12:00:00Z'"/>
```
and run `rake` to generate `agenda.html`. It will be 4 days in `agenda.html`: `30+30+1 - (30+27) == 4`, but actually it is 2 days: `30+28+1 - (30+27) == 2`.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#336](https://github.com/zerocracy/datum/issues/336) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/datum/issues/336#issuecomment-392309310))

@g4s8 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#336](https://github.com/zerocracy/datum/issues/336) is [in scope](http://www.zerocracy.com/policy.html#14) for 2mon
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Fdatum%23336%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by proshin-roman** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/zerocracy/datum/issues/336#issuecomment-396604798))

@proshin-roman The user @proshin-roman[/z](https://www.0crat.com/u/proshin-roman) resigned from [#336](https://github.com/zerocracy/datum/issues/336), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by 0crat** [comment]
The job [#336](https://github.com/zerocracy/datum/issues/336) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1651114205); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment]
@0crat wait while #345 is resolved

**Comment by 0crat** [comment]
> @0crat wait while #345 is resolved ([here](https://github.com/zerocracy/datum/issues/336#issuecomment-397879930))

@paulodamaso The impediment for [#336](https://github.com/zerocracy/datum/issues/336) was registered successfully by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by paulodamaso** [comment]
@g4s8 Merged, please close.

**Comment by g4s8** [comment]
@paulodamaso thanks

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#336](https://github.com/zerocracy/datum/issues/336) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality good
