### ISSUE TITLE
Allow lower contribution values

### ISSUE THREAD

**Issue by filfreire** [zerocracy/datum#338]
Picking up from issue #212, I suggest we allow contributions of lower fund values, below $64, to allow people with lower possibilities to contribute:

Example values: $4, $8, $16, $32

/cc @yegor256 @g4s8

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@filfreire 4 and 8 are too low. I added 16 and 32: https://github.com/zerocracy/farm/commit/31b5759681a56075bde826add7c80956432fea65

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
