### ISSUE TITLE
It is not clear what "All problems found by the code reviewer were addressed by the pull request author" means 

### ISSUE THREAD

**Issue by elenavolokhova** [zerocracy/datum#342]
We have a statement in our Policy:
> All problems found by the code reviewer were addressed by the pull request author

But it is not clear what reaction is acceptable for issues found by REV. For example in [#856](https://github.com/yegor256/cactoos/pull/856) REV found some issues, but DEV didn't fix it with valuable arguments. 

How should we handle such situations? Formally "3 issues" rule was followed, I can not say that REV just accepted PR. But it's quality was not improved after such review.

I think we need some clarification in statement: 
> All problems found by the code reviewer were addressed by the pull request author

It should say clearly should these problems be fixed or just explained. 
Or maybe we should add some clarification in other Policy statement?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@elenavolokhova see: https://github.com/zerocracy/zerocracy.github.io/commit/16dc5fa079cac405eb6283ce710f3c121e09d16e Better?

**Comment by elenavolokhova** [comment]
@yegor256 Yes, much better, thank you!
