### ISSUE TITLE
No badges in schema

### ISSUE THREAD

**Issue by g4s8** [zerocracy/datum#343]
According to https://github.com/zerocracy/farm/issues/848 issue we have to store badges for a people. I think we can store it in `people.xml`, so we need a new field here.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@0crat assign @carlosmiranda

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by carlosmiranda** [comment]
@g4s8 see PR #346

**Comment by carlosmiranda** [comment]
@0crat wait for PR #346 to be merged

**Comment by 0crat** [comment]
> @0crat wait for PR #346 to be merged ([here](https://github.com/zerocracy/datum/issues/343#issuecomment-394214416))

@carlosmiranda The impediment for [#343](https://github.com/zerocracy/datum/issues/343) was registered successfully by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by carlosmiranda** [comment]
@g4s8 #346 merged, can we close this?

**Comment by g4s8** [comment]
@carlosmiranda sure, thanks

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
