### ISSUE TITLE
Zold is not supported as a wallet type

### ISSUE THREAD

**Issue by g4s8** [zerocracy/datum#344]
Wallet type in `people.xsd` has enumeration restriction:
```xml
<xs:restriction base="xs:string">
  <xs:enumeration value="paypal"/>
  <xs:enumeration value="btc"/>
  <xs:enumeration value="eth"/>
  <xs:enumeration value="bch"/>
  <xs:enumeration value="ltc"/>
</xs:restriction>
```
to support Zold as discussed in zerocracy/farm#1074 we need to add new wallet type: `zld`.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by g4s8** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/zerocracy/datum/issues/344#issuecomment-395773122))

@g4s8 Job [#344](https://github.com/zerocracy/datum/issues/344) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#344](https://github.com/zerocracy/datum/issues/344) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2310061860); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by krzyk** [comment]
@g4s8 `zld` is already in this enumeration: https://github.com/zerocracy/datum/blob/master/xsd/pmo/people.xsd#L28-L35

**Comment by g4s8** [comment]
@krzyk looks like I've fixed it with https://github.com/zerocracy/farm/issues/1350 bug

**Comment by 0crat** [comment]
Job was finished in 13 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#344](https://github.com/zerocracy/datum/issues/344) is now out of scope

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
