### ISSUE TITLE
rake fails with error

### ISSUE THREAD

**Issue by t-izbassar** [zerocracy/datum#345]
Trying to build the project with `rake`, but getting an error:

> rake --trace
rake aborted!
LoadError: cannot load such file -- redcarpet
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/home/tolegen/Projects/workspace/0crat/zerocracy/datum/Rakefile:26:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:28:in `load'
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:28:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:689:in `raw_load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:94:in `block in load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:93:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:77:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:75:in `run'
/usr/bin/rake:27:in `main'

My Environment is:
`ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]`

`gem list | grep rake` command gives me: `rake (12.3.1, 10.5.0)`

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@t-izbassar did you try `bundle install` (`gem install bundler` if you doesn't have it) before `rake`?

**Comment by t-izbassar** [comment]
@g4s8 yes. I've updated with `bundle update`. I had to switch ruby version in `Gemfile` from `2.3.3` to `2.3.1`. Now I've got different error:

> rake --trace
```** Invoke default (first_time)
** Invoke clean (first_time)
** Execute clean
rm -r target
** Invoke xsd (first_time)
** Execute xsd
Checking XML files for XSD validity...
........................................................................................................................................
All 136 XML/XSD files are clean
** Invoke xslversions (first_time)
** Execute xslversions
Checking versions of XSL files...
** Invoke xsl (first_time)
** Execute xsl
Checking XML and XSL files...
Error: Unable to access jarfile /home/tolegen/.m2/repository/net/sf/saxon/Saxon-HE/9.8.0-8/Saxon-HE-9.8.0-8.jar
<?xml version="1.0"?>
rake aborted!
HTML <section> absent in HTML from xml/pmo/agenda/simple.xml
/home/tolegen/Projects/workspace/0crat/zerocracy/datum/Rakefile:149:in `block (2 levels) in <top (required)>'
/home/tolegen/Projects/workspace/0crat/zerocracy/datum/Rakefile:137:in `each'
/home/tolegen/Projects/workspace/0crat/zerocracy/datum/Rakefile:137:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:237:in `block in invoke_prerequisites'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:235:in `each'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:235:in `invoke_prerequisites'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:212:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/var/lib/gems/2.3.0/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/var/lib/gems/2.3.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => default => xsl
```

**Comment by g4s8** [comment]
@t-izbassar you got this error because you doesn't have `net.sf.saxon` jar, you can install it with `mvn dependency:get -DgroupId=net.sf.saxon -DartifactId=Saxon-HE -Dversion=9.8.0-8`

**Comment by g4s8** [comment]
@t-izbassar but you're right, it's not clear how to setup environment for this project, I think we should add documentation about it in readme

**Comment by g4s8** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/zerocracy/datum/issues/345#issuecomment-394120489))

@g4s8 Job [#345](https://github.com/zerocracy/datum/issues/345) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar)

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/datum/issues/345#issuecomment-395513080))

@g4s8 The job [#345](https://github.com/zerocracy/datum/issues/345) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1581816364); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@t-izbassar can you try to install all tools from this PR #348?

**Comment by t-izbassar** [comment]
@g4s8 works, with the downloaded dependency of Saxon.

**Comment by g4s8** [comment]
@t-izbassar README updated, can we close now?

**Comment by t-izbassar** [comment]
@g4s8 yep, it's more helpful now. Still, I don't get why ruby uses some mvn dependency from file system )

**Comment by g4s8** [comment]
@t-izbassar it uses Saxon jar for tests because ruby and java has different xslt engine versions: `ruby: 1.0` `Saxon: 3.0`

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#345](https://github.com/zerocracy/datum/issues/345) is now out of scope
