### ISSUE TITLE
Job inspector element

### ISSUE THREAD

**Issue by g4s8** [zerocracy/datum#347]
We need new agenda field: `inspector`, as discussed here: https://github.com/zerocracy/farm/issues/911#issuecomment-380540834 this is optional element with `login` type. Don't forget to update `agenda.xsl`.

**Comment by g4s8** [comment]
@0crat assign @carlosmiranda

**Comment by 0crat** [comment]
> @0crat assign @carlosmiranda  ([here](https://github.com/zerocracy/datum/issues/347#issuecomment-395514458))

@g4s8 The job [#347](https://github.com/zerocracy/datum/issues/347) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1581821488); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by carlosmiranda** [comment]
@g4s8 can we close this now? Fixed in #350.

**Comment by carlosmiranda** [comment]
@g4s8 ping

**Comment by g4s8** [comment]
@carlosmiranda thanks

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@2a5ea468-7e77-489c-80d0-c8be03a5d7e1, thread: AsyncFlush-8
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "verbosity/carlosmiranda.xml" in "PMO" in 1min: 61df0a5983f1/4s/0/1/true/false by QuartzScheduler_Worker-1
```

[0.22.7](https://github.com/zerocracy/farm): CID: [1710959567](https://www.0crat.com/C3NDPUA8L/1710959567), Type: "Close job", Author: "g4s8"

**Comment by carlosmiranda** [comment]
@0crat status

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@a20fdf63-8643-4773-9ea4-95ef1507c623, thread: pool-56-thread-1
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 1min: 8c5662c87aa6/31min/0/1/true/false by AsyncFlush-2
```

[0.22.19](https://github.com/zerocracy/farm): Issue: zerocracy/datum#347, Comment: 398914075

**Comment by carlosmiranda** [comment]
@0crat status

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@aa0fe21a-ccc8-4a0f-920f-f4c2aaf4a20f, thread: pool-136-thread-1
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 2min: 6cc77ffce735/10min/0/2/true/false by zerocrat_bot Telegram Executor
```

[0.22.25](https://github.com/zerocracy/farm): Issue: zerocracy/datum#347, Comment: 399083959

**Comment by ypshenychka** [comment]
@0crat ping

**Comment by carlosmiranda** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat ping ([here](https://github.com/zerocracy/datum/issues/347#issuecomment-399101522))

@ypshenychka Can't understand "ping", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by 0crat** [comment]
> @0crat status  ([here](https://github.com/zerocracy/datum/issues/347#issuecomment-399415431))

@carlosmiranda This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#347](https://github.com/zerocracy/datum/issues/347) is [in scope](http://www.zerocracy.com/policy.html#14) for 15days
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @g4s8[/z](https://www.0crat.com/u/g4s8): This user reported the ticket
  * The job is waiting quality review verdict by @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) for 2days
  * @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Fdatum%23347%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
The job [#347](https://github.com/zerocracy/datum/issues/347) is now out of scope
