### ISSUE TITLE
Need "agenda" and "speed" element in people.xml

### ISSUE THREAD

**Issue by carlosmiranda** [zerocracy/datum#353]
We need `agenda` and `speed` elements in `people.xml`. This is required because of https://github.com/zerocracy/farm/issues/1121.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/datum/issues/353#issuecomment-398384485))

@g4s8 The job [#353](https://github.com/zerocracy/datum/issues/353) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1701248257); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@carlosmiranda we already have an element for agenda, but it calls `jobs` here. I added `speed` element, please see #354 PR.

**Comment by g4s8** [comment]
@rultor release, tag=`0.61.2`

**Comment by carlosmiranda** [comment]
@g4s8 thanks! Closing now, release failed though. https://github.com/zerocracy/datum/issues/353#issuecomment-398696839

**Comment by g4s8** [comment]
@rultor release, tag=`0.61.2`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@2a5ea468-7e77-489c-80d0-c8be03a5d7e1, thread: AsyncFlush-8
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "verbosity/g4s8.xml" in "PMO" in 1min: 61df0a5983f1/7s/0/3/true/false by QuartzScheduler_Worker-1
```

[0.22.7](https://github.com/zerocracy/farm): CID: [1711019629](https://www.0crat.com/C3NDPUA8L/1711019629), Type: "Close job", Author: "carlosmiranda"

**Comment by carlosmiranda** [comment]
@0crat status

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@a20fdf63-8643-4773-9ea4-95ef1507c623, thread: pool-52-thread-1
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 1min: 8c5662c87aa6/28min/0/3/true/false by AsyncFlush-2
```

[0.22.19](https://github.com/zerocracy/farm): Issue: zerocracy/datum#353, Comment: 398913958

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@a20fdf63-8643-4773-9ea4-95ef1507c623, thread: pool-52-thread-1
com.zerocracy.radars.github.ReSafe[82] java.io.IOException: java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 1min: 8c5662c87aa6/28min/0/3/true/false by AsyncFlush-2
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 1min: 8c5662c87aa6/28min/0/3/true/false by AsyncFlush-2
```

[0.22.19](https://github.com/zerocracy/farm): Issue: zerocracy/datum#353, Action: `created`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@a20fdf63-8643-4773-9ea4-95ef1507c623, thread: pool-57-thread-1
com.zerocracy.radars.github.ReSafe[82] java.io.IOException: java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 1min: 8c5662c87aa6/30min/0/3/true/false by AsyncFlush-2
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 1min: 8c5662c87aa6/30min/0/3/true/false by AsyncFlush-2
```

[0.22.19](https://github.com/zerocracy/farm): Issue: zerocracy/datum#353, Action: `created`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@a20fdf63-8643-4773-9ea4-95ef1507c623, thread: pool-56-thread-1
com.zerocracy.radars.github.ReSafe[82] java.io.IOException: java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 1min: 8c5662c87aa6/31min/0/1/true/false by AsyncFlush-2
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "people.xml" in "PMO" in 1min: 8c5662c87aa6/31min/0/1/true/false by AsyncFlush-2
```

[0.22.19](https://github.com/zerocracy/farm): Issue: zerocracy/datum#353, Action: `created`

**Comment by carlosmiranda** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/zerocracy/datum/issues/353#issuecomment-399050727))

@carlosmiranda This is what I know about this job in [C3NDPUA8L](https://www.0crat.com/p/C3NDPUA8L), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#353](https://github.com/zerocracy/datum/issues/353) is [in scope](http://www.zerocracy.com/policy.html#14) for 2days
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3NDPUA8L?q=%7Bjob%3A%27gh%3Azerocracy%2Fdatum%23353%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
The job [#353](https://github.com/zerocracy/datum/issues/353) is now out of scope
