### ISSUE TITLE
Additional info in pm/staff/roles

### ISSUE THREAD

**Issue by llorllale** [zerocracy/datum#356]
Let's include this information in `pm/staff/roles`:

* Available funds for continuing assignment and scoping of tasks. This is different from the total overall funding of the project.
* Vacation status of performer (row can be grayed out just like in the *Team* view)
* A new **Jobs** column with the ratio `current_jobs/max_jobs`

As `ARC`, these three pieces of information in the same place as staff and roles will help me better understand the flow of tasks, such as situations when there are open tasks and sufficient funding but no tasks are being assigned automatically.

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@llorllale I don't agree that `roles.xml` is best place to store additional info about users, because it's simple data file with purpose to store roles. Maybe we can show it on project page or create new page for it? Anyhow I think it's better to re-submit this ticket to https://github.com/zerocracy/farm repo.

**Comment by llorllale** [comment]
@g4s8 sure; I also found it weird but didn't know where else to put it.

My problem is simply that as `ARC` I need all that information in one place in order to ease understanding of my project's current work capacity. I re-phased it in those terms in zerocracy/farm#1293.

Thanks

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#356` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
