### ISSUE TITLE
Run XSL tests with Saxon instead of Nokogiri.

### ISSUE THREAD

**Issue by paulodamaso** [zerocracy/datum#365]
At the moment we are using `Nokogiri` for running `XSL` tests in `Rakefile`. As discovered in #315 `Nokogiri` provided limited support to `XSLT` 2.0 and `XPATH` 2.0, which limits our choices of functions and tags for `XSL` transformations.

We should run the tests in `Rakefile` using `Saxon` processor, like used in `Rakefile` to transform in `html` files (line 145).

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/datum/issues/365#issuecomment-402512454))

@g4s8 The job [#365](https://github.com/zerocracy/datum/issues/365) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1851545577); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@paulodamaso it was done in #366, can we close?

**Comment by paulodamaso** [comment]
@g4s8 Yes, but please take a look at https://github.com/zerocracy/datum/issues/371 , looks like one of the problems is related to the changes made to `Rakefile` in #366.
