### ISSUE TITLE
Need a negligence elements

### ISSUE THREAD

**Issue by krzyk** [zerocracy/datum#367]
To implement https://github.com/zerocracy/farm/issues/1141 I need to following:
- negliegence.xsd that will have elements "job", "project", datetime element and version (similar to verbosity, but without count)
- negliegence.xsl that will show a list of negliegence events

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@krzyk does this xml OK for you?
```xml
<verbosity version="1" updated="2017-08-08T22:22:22.222Z">
  <order job="gh:test/test#1">
    <project>ABCDEF123</project>
    <added>2016-12-29T09:03:21.684Z</added>
  </order>
  <order job="gh:test/test#2">
    <project>ABCDEF123</project>
    <added>2016-12-30T09:03:21.684Z</added>
  </order>
</verbosity>
```

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/datum/issues/367#issuecomment-403213335))

@g4s8 The job [#367](https://github.com/zerocracy/datum/issues/367) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1881252239); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @g4s8[/z](https://www.0crat.com/u/g4s8) is on vacation; this ticket may be delayed; there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by krzyk** [comment]
@g4s8 looks good

**Comment by g4s8** [comment]
@rultor release, tag=`0.61.7`

**Comment by g4s8** [comment]
@krzyk please close this job, you can use negligence in `0.61.7` version.

**Comment by krzyk** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#367](https://github.com/zerocracy/datum/issues/367) is now out of scope
