### ISSUE TITLE
releases.xml

### ISSUE THREAD

**Issue by g4s8** [zerocracy/datum#372]
Let's add `releases.xml` project file to keep releases details for #1366, it should contain release tag and publish date:
```xml
<releases>
  <release repo="test/test" tag="1.2.3">
    <publish>2018-01-01T00:00:00.123Z</publish>
  </release>
</releases>
```

`repo` + `tag` should be unique across all releases in file.

**Comment by g4s8** [comment]
@0crat assign @carlosmiranda

**Comment by 0crat** [comment]
> @0crat assign @carlosmiranda  ([here](https://github.com/zerocracy/datum/issues/372#issuecomment-403745273))

@g4s8 The job [#372](https://github.com/zerocracy/datum/issues/372) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/1910838432); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by carlosmiranda** [comment]
@g4s8 see PR #373

**Comment by carlosmiranda** [comment]
@g4s8 PR #372 merged, may we close this now?

**Comment by g4s8** [comment]
@carlosmiranda thanks

**Comment by g4s8** [comment]
@rultor release, tag=`0.62.1`

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#372](https://github.com/zerocracy/datum/issues/372) is now out of scope

**Comment by g4s8** [comment]
@rultor release, tag=`0.61.2`

**Comment by g4s8** [comment]
@rultor release, tag=`0.62.2`

**Comment by ypshenychka** [comment]
@0crat quality good
