### ISSUE TITLE
Blanks, Verbosity and Speed should contain creation time

### ISSUE THREAD

**Issue by krzyk** [zerocracy/datum#378]
Blanks, Verbosity and Speed (like all future metrics) should have a `added` field that will contain a datetime when given metric item was added. `added` field already exists in Negligence and Awards.

This is needed to restrict the metric to the last 90 days (or any other date range that we might have in policy) (see https://github.com/zerocracy/farm/issues/1099)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/datum/issues/378#issuecomment-408623441))

@g4s8 The job [#378](https://github.com/zerocracy/datum/issues/378) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/C3NDPUA8L/2091748741); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
@krzyk it was fixed in #379, can we close?

**Comment by krzyk** [comment]
@g4s8 thanks

**Comment by 0crat** [comment]
Job was finished in 15 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#378](https://github.com/zerocracy/datum/issues/378) is now out of scope
