### ISSUE TITLE
Update website

### ISSUE THREAD

**Issue by weirdgiraffe** [zerocracy/datum#40]
Website says : "come back in May 2017". Today is 24 May 2017, expectation expires in 7 days

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@weirdgiraffe fixed in https://github.com/zerocracy/zerocracy.github.io/commit/1e3af887748f101c2188996ca4d9de5bcad760c0 Thanks for reminding :)

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#40` was not in scope
