### ISSUE TITLE
Provide info how to setup 0crat for OSS project

### ISSUE THREAD

**Issue by ruspl-afed** [zerocracy/datum#408]
I'm trying to setup 0crat for OSS project hosted at GitHub 
After adding 0crat to my [organization](https://github.com/arsysop) it still requires me to be invited
As I know it is planned #316 to add some Q&A info to stackexchange.com but for today it is not yet covered there

Please provide a how-to for OSS projects

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment]
@ruspl-afed[/z](https://www.0crat.com/u/ruspl-afed) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3NDPUA8L) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by g4s8** [comment]
@ruspl-afed if you want to bootstrap a new project, you need to check this page: https://www.zerocracy.com/pfaq.html

**Comment by ruspl-afed** [comment]
@g4s8 the link doesn't contain OSS-specific info and rout to the standard commercial case. If you don't have an option for OSS to use 0crat for free please declare it more clear.

**Comment by g4s8** [comment]
@ruspl-afed the only difference between OSS and commercial projects is that 0crat will not charge OSS project, but will charge commercial project for each ticket. The bootstrap process is the same for both kind of projects. You can't set OSS option on your side, 0crat will understand it by self via GitHub API.

**Comment by ruspl-afed** [comment]
```
Alexander Fedorov 10:12 AM
@0crat bootstrap

0cratAPP 10:12 AM
You must be invited in order to do that, see [§1](http://www.zerocracy.com/policy.html#1)
```
So, I have no chance to use 0crat for OSS without being invited
And then probably I will need to work hard to gain +1024 to be blessed for `bootstrap` permission
And then who knows what, may be non-refundable fee to submit an RFP.
Well, it doesn't look like "free for OSS" as stated at GitHub market, please update your documentation accordingly.

P.S. You can compare with some really "free for OSS" service like Travis CI

**Comment by g4s8** [comment]
@ruspl-afed you just need to find adviser with high reputation like for any other project, you're not supposed to bootstrap it by yourself if you don't have a lot of reputation points. See https://www.zerocracy.com/pfaq.html

> PO invites adviser (a person with high reputation > 1024), this person will bootstrap 0crat, configure it and assign roles. It can be done by project architect if he/she has enough reputation.

**Comment by ruspl-afed** [comment]
@g4s8 I'm not trying to discuss the zerocracy policies, it is up to you how to define it
I have another message: the 0crat usage is declared "Free" for OSS projects and in fact it is ***not***

@yegor256 may be I'm missing something but in its current state it is better to describe your OSS support much more clear. Otherwise the confidence will be broken with hidden payments required to use the 0crat for OSS at GitHub.

**Comment by g4s8** [comment]
@ruspl-afed it seems you didn't get it. Zerocracy is absolutely free for OSS, you don't need to pay anything to set it up. You may pay programmers via Zerocracy for completed jobs, but it's optional and up to you.

**Comment by ruspl-afed** [comment]
@g4s8 this is good to know. From what I can get from docs and experiments, the setup may be free:
1) for "invited" person that managed to earn reputation >1024 and can perfrom bootstrap
2) for one who managed to convince "adviser" to perform a bootstrap for free
Am I missing any other ways?

**Comment by g4s8** [comment]
@ruspl-afed it's correct. We have strong reasons to force people to find advisers if they don't have enough reputation, since adviser will be responsible to explain Zerocracy workflow to PO and will help to configure and manage 0crat bot for the project.

**Comment by ruspl-afed** [comment]
@g4s8 ok, so there is really no difference in setting up 0cracy for OSS. 
I think we can close this one. Thank you for your time! Hope you will get `quality good` for it.

If any of respected advisers is interested to promote 0cracy in OSS communities - I'm still open for collaboration

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#408` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
