### ISSUE TITLE
Lack of documentation for schema changes

### ISSUE THREAD

**Issue by g4s8** [zerocracy/datum#51]
It's not clear how to add new `xsd` files or change existing. 
Also I'd like to see some explanation of `xml` and `upgrades` folders,
how to name validation `xml` files and upgrade `xsl` files.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/datum/issues/51#issuecomment-316805823))

@yegor256 Job `gh:zerocracy/datum#51` assigned to @yegor256, please go ahead.

**Comment by yegor256** [comment]
@g4s8 see c5568a0 Good enough?

**Comment by g4s8** [comment]
@yegor256 yes, it looks good

**Comment by yegor256** [comment]
@g4s8 please, close the ticket than :)

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#51` is out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is +270
