### ISSUE TITLE
additional XSL

### ISSUE THREAD

**Issue by yegor256** [zerocracy/datum#54]
We need more XSL documents.

**Comment by yegor256** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/datum/issues/54#issuecomment-317831814))

@yegor256 Job `gh:zerocracy/datum#54` assigned to @yegor256, please go ahead.

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+585](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `0.29.2`

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#54` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+615](http://www.0crat.com/u/yegor256).
