### ISSUE TITLE
issue out was fail

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#81]
https://github.com/DronMDF/telebot/issues/2#issuecomment-321761156

java.lang.IllegalStateException: Failed to acquire "2017/08/C6KLDT6QG/orders.xml" in 20s

More in issue.

PS: But issue was out.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@DronMDF we're looking at it now...

**Comment by yegor256** [comment]
@DronMDF it's fixed, please close

**Comment by DronMDF** [comment]
@yegor256 This is a fixed. Thank's.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:zerocracy/datum#81`.

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#81` is not in scope.
