### ISSUE TITLE
notify_user must notify all links

### ISSUE THREAD

**Issue by yegor256** [zerocracy/datum#83]
At the moment `Notify User` only sends a message to the user in Slack. This is not correct, since the user may have other aliases, like Telegram, for example. We must take them all from the `People` and notify the user through all of them.

**Comment by yegor256** [comment]
@0crat assign @g4s8

**Comment by 0crat** [comment]
> @0crat assign @g4s8  ([here](https://github.com/zerocracy/datum/issues/83#issuecomment-322182946))

@yegor256 Job `gh:zerocracy/datum#83` assigned to @g4s8, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+1665](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@g4s8 oops, wrong repo

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#83` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @g4s8, total is [+1020](http://www.0crat.com/u/g4s8).
