### ISSUE TITLE
Cannot set rate

### ISSUE THREAD

**Issue by amihaiemil** [zerocracy/datum#84]
I open the direct, private chat with 0crat, and type "rate $dd" -- it responds with "your rate is 0"

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@0crat assign @g4s8

**Comment by 0crat** [comment]
> @0crat assign @g4s8  ([here](https://github.com/zerocracy/datum/issues/84#issuecomment-322308041))

@yegor256 Job `gh:zerocracy/datum#84` assigned to @g4s8, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by g4s8** [comment]
@amihaiemil "rate" was fixed. You can use this syntax to set it: `rate set $<value>`

**Comment by amihaiemil** [comment]
@g4s8 This seems to be fixed, but ``rate set $<value>`` cannot be parsed, Response is: ``Oops! Can't parse cash value pair "set"``

However, ``rate $<value`` works fine.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#84` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @g4s8, total is [+2440](http://www.0crat.com/u/g4s8).
