### ISSUE TITLE
Human-readable timestamps

### ISSUE THREAD

**Issue by g4s8** [zerocracy/datum#85]
Now we can see our awards and agenda timestamps in ISO-8601 format, e.g. this one: 2017-08-14T16:01:33.038Z.
I think it should be formatted like this: 14 aug 2017 16:33.
Also it would be better to show this time in browser timezone, not UTC.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/zerocracy/datum/issues/85#issuecomment-322423900))

@yegor256 Job `gh:zerocracy/datum#85` is in scope.

**Comment by 0crat** [comment]
+15 points just awarded to @g4s8, total is [+1035](http://www.0crat.com/u/g4s8).

**Comment by yegor256** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/zerocracy/datum/issues/85#issuecomment-322454575))

@yegor256 Job `gh:zerocracy/datum#85` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by yegor256** [comment]
@rultor release, tag is `0.36.2`

**Comment by yegor256** [comment]
@g4s8 seem to be fine now, please check

**Comment by g4s8** [comment]
@yegor256 yes, thanks

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#85` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+1860](http://www.0crat.com/u/yegor256).
