### ISSUE TITLE
Show winner in elections

### ISSUE THREAD

**Issue by yegor256** [zerocracy/datum#89]
Let's show the winner.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#89` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+1875](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
Can't do it with XSLT 1.0, unfortunately :(

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#89` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+1920](http://www.0crat.com/u/yegor256).
