### ISSUE TITLE
Different usernames in slack and github

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#91]
User tanyaerm from slack invited to project. 
On Roles page i look tanyaerm name and github url. This is wrong and not worked.

Next, a try to assign issue on github.
0crat say me 'tanika95' is not in project.

If i'll try assign tanyaerm - 0crat does not say anything. This name used in Roles!

What name and where should I use it?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@DronMDF we must everywhere use GitHub names, not Slack ones. We will try to add extra checks now, to make sure you get error messages when trying to use non-GitHub IDs.

**Comment by DronMDF** [comment]
One moment. If bot talk with user on slack, github name is not work... in other places gh name is ok.

**Comment by DronMDF** [comment]
@yegor256 
I'm completely confused...
In the slack users come with their slack name.
Do I need to assign roles through slack name?
Should I use these github names in the slack?

**Comment by DronMDF** [comment]
By policy invite and assigning should be do over github login.
This is right?

**Comment by yegor256** [comment]
@DronMDF yes, we're not using Slack names anywhere. Everything works by GitHub names only. So, always use GitHub names please.

**Comment by DronMDF** [comment]
@yegor256 i'll try it in near two week. If all ok, i close this ticket.

**Comment by DronMDF** [comment]
@yegor256 I think it works. Thank's

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:zerocracy/datum#91`.

**Comment by 0crat** [comment]
Oops! Job `gh:zerocracy/datum#91` is not in scope.
