### ISSUE TITLE
User points

### ISSUE THREAD

**Issue by g4s8** [zerocracy/datum#92]
It's not clear what is "points" and how they are related with actual cash. I think it should be written in policy page.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#92` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @g4s8, total is [+1380](http://www.0crat.com/u/g4s8).

**Comment by yegor256** [comment]
@g4s8 check ca861d7 Good enough?

**Comment by g4s8** [comment]
@yegor256 yes, thanks!

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#92` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+2415](http://www.0crat.com/u/yegor256).
