### ISSUE TITLE
Refuse of the issue does not work.

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#95]
https://github.com/DronMDF/telebot/issues/2#issuecomment-323709290

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#95` assigned to @carlosmiranda, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@carlosmiranda resigned from `gh:zerocracy/datum#95`, please stop working.

**Comment by DronMDF** [comment]
Refuse is work. Done.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:zerocracy/datum#95`.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#95` is now out of scope.
