### ISSUE TITLE
0crat does not pay for review.

### ISSUE THREAD

**Issue by DronMDF** [zerocracy/datum#96]
PR https://github.com/DronMDF/telebot/pull/5 is closed, but 0crat does not wake up for give money.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#96` assigned to @carlosmiranda, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by DronMDF** [comment]
0crat does not close this request for youself.
A found this work in WBS.
Other PR are payed +15.

This was a unstable moment.

I close this issue?

**Comment by 0crat** [comment]
@carlosmiranda resigned from `gh:zerocracy/datum#96`, please stop working.

**Comment by yegor256** [comment]
@DronMDF I believe it's fixed now, please check all your pull requests, they must be out of WBS now

**Comment by DronMDF** [comment]
@yegor256 ARC +15, DEV +30. It seems that everything is fine. Thank's

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:zerocracy/datum#96`.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#96` is now out of scope.
