### ISSUE TITLE
Rake build failure (NoMethodError: undefined method `iso8601')

### ISSUE THREAD

**Issue by carlosmiranda** [zerocracy/datum#97]
Project build is failing. See: https://travis-ci.org/zerocracy/datum/builds/267153828

```
NoMethodError: undefined method `iso8601' for 2017-08-22 12:01:07 +0000:Time
/home/travis/build/zerocracy/datum/Rakefile:146:in `block (2 levels) in <top (required)>'
/home/travis/build/zerocracy/datum/Rakefile:133:in `each'
/home/travis/build/zerocracy/datum/Rakefile:133:in `block in <top (required)>'
/home/travis/.rvm/gems/ruby-2.3.3/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => xsl
(See full trace by running task with --trace)
```

This can be fixed by adding the following `require` statement to the Rakefile:

```
require 'time'
```

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#97` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @carlosmiranda, total is [+795](http://www.0crat.com/u/carlosmiranda).

**Comment by yegor256** [comment]
@carlosmiranda I believe it's fixed already, right?

**Comment by carlosmiranda** [comment]
@yegor256 yes, I had to incorporate it in #98 or else I would not have been able to build it. Thanks, closing it now.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#97` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+2220](http://www.0crat.com/u/yegor256).
