### ISSUE TITLE
XML consistency rules

### ISSUE THREAD

**Issue by yegor256** [zerocracy/datum#99]
Let's introduce consistency rules between XML documents, to make sure they all are in order. For example, an `<order>` can't exist in `orders.xml` if a respective `<job>` is not present in the `wbs.xml`.

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#99` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+2445](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `0.38`

**Comment by yegor256** [comment]
@rultor release, tag is `0.38`

**Comment by yegor256** [comment]
@rultor release, tag is `0.38`

**Comment by 0crat** [comment]
Job `gh:zerocracy/datum#99` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+2505](http://www.0crat.com/u/yegor256).
